window.GRAPH = {
  "nodes": [
    {"id":"5","label":"5","role":"value"},
    {"id":"PARIS","label":"PARIS","role":"value"},
    {"id":"TOKYO","label":"TOKYO","role":"value"},
    {"id":"arc","label":"arc","role":"value"},
    {"id":"a|r|c","label":"a|r|c","role":"value"},
    {"id":"bat","label":"bat","role":"value"},
    {"id":"b|a|t","label":"b|a|t","role":"value"},
    {"id":"cat","label":"cat","role":"value"},
    {"id":"cut()","label":"cut()","role":"function"},
    {"id":"cut(arc)","label":"cut(arc)","role":"application"},
    {"id":"cut(bat)","label":"cut(bat)","role":"application"},
    {"id":"cut(cat)","label":"cut(cat)","role":"application"},
    {"id":"cut(lima)","label":"cut(lima)","role":"application"},
    {"id":"cut(paris)","label":"cut(paris)","role":"application"},
    {"id":"cutWords()","label":"cutWords()","role":"function"},
    {"id":"cutWords(paris france)","label":"cutWords(paris france)","role":"application"},
    {"id":"c|a|t","label":"c|a|t","role":"value"},
    {"id":"firstLetter()","label":"firstLetter()","role":"function"},
    {"id":"firstLetter(paris)","label":"firstLetter(paris)","role":"application"},
    {"id":"firstLetter(tokyo)","label":"firstLetter(tokyo)","role":"application"},
    {"id":"length()","label":"length()","role":"function"},
    {"id":"length(paris)","label":"length(paris)","role":"application"},
    {"id":"length(tokyo)","label":"length(tokyo)","role":"application"},
    {"id":"lima","label":"lima","role":"value"},
    {"id":"l|i|m|a","label":"l|i|m|a","role":"value"},
    {"id":"p","label":"p","role":"value"},
    {"id":"paris","label":"paris","role":"value"},
    {"id":"paris france","label":"paris france","role":"value"},
    {"id":"paris|france","label":"paris|france","role":"value"},
    {"id":"p|a|r|i|s","label":"p|a|r|i|s","role":"value"},
    {"id":"t","label":"t","role":"value"},
    {"id":"tokyo","label":"tokyo","role":"value"},
    {"id":"upper()","label":"upper()","role":"function"},
    {"id":"upper(paris)","label":"upper(paris)","role":"application"},
    {"id":"upper(tokyo)","label":"upper(tokyo)","role":"application"}
  ],
  "edges": [
    {"from":"arc","to":"cut(arc)"},
    {"from":"bat","to":"cut(bat)"},
    {"from":"cat","to":"cut(cat)"},
    {"from":"cut()","to":"cut(arc)"},
    {"from":"cut()","to":"cut(bat)"},
    {"from":"cut()","to":"cut(cat)"},
    {"from":"cut()","to":"cut(lima)"},
    {"from":"cut()","to":"cut(paris)"},
    {"from":"cut(arc)","to":"a|r|c"},
    {"from":"cut(bat)","to":"b|a|t"},
    {"from":"cut(cat)","to":"c|a|t"},
    {"from":"cut(lima)","to":"l|i|m|a"},
    {"from":"cut(paris)","to":"p|a|r|i|s"},
    {"from":"cutWords()","to":"cutWords(paris france)"},
    {"from":"cutWords(paris france)","to":"paris|france"},
    {"from":"firstLetter()","to":"firstLetter(paris)"},
    {"from":"firstLetter()","to":"firstLetter(tokyo)"},
    {"from":"firstLetter(paris)","to":"p"},
    {"from":"firstLetter(tokyo)","to":"t"},
    {"from":"length()","to":"length(paris)"},
    {"from":"length()","to":"length(tokyo)"},
    {"from":"length(paris)","to":"5"},
    {"from":"length(tokyo)","to":"5"},
    {"from":"lima","to":"cut(lima)"},
    {"from":"paris","to":"cut(paris)"},
    {"from":"paris","to":"firstLetter(paris)"},
    {"from":"paris","to":"length(paris)"},
    {"from":"paris","to":"upper(paris)"},
    {"from":"paris france","to":"cutWords(paris france)"},
    {"from":"tokyo","to":"firstLetter(tokyo)"},
    {"from":"tokyo","to":"length(tokyo)"},
    {"from":"tokyo","to":"upper(tokyo)"},
    {"from":"upper()","to":"upper(paris)"},
    {"from":"upper()","to":"upper(tokyo)"},
    {"from":"upper(paris)","to":"PARIS"},
    {"from":"upper(tokyo)","to":"TOKYO"}
  ],
  "pivot": {
    "subjects": [
      "arc",
      "bat",
      "cat",
      "lima",
      "paris",
      "paris france",
      "tokyo"
    ],
    "columns": [
      "cut",
      "cutWords",
      "firstLetter",
      "length",
      "upper"
    ],
    "cells": [
      {"s":"arc","c":"cut","res":"a|r|c","app":"cut(arc)"},
      {"s":"bat","c":"cut","res":"b|a|t","app":"cut(bat)"},
      {"s":"cat","c":"cut","res":"c|a|t","app":"cut(cat)"},
      {"s":"lima","c":"cut","res":"l|i|m|a","app":"cut(lima)"},
      {"s":"paris","c":"cut","res":"p|a|r|i|s","app":"cut(paris)"},
      {"s":"paris","c":"firstLetter","res":"p","app":"firstLetter(paris)"},
      {"s":"paris","c":"length","res":"5","app":"length(paris)"},
      {"s":"paris","c":"upper","res":"PARIS","app":"upper(paris)"},
      {"s":"paris france","c":"cutWords","res":"paris|france","app":"cutWords(paris france)"},
      {"s":"tokyo","c":"firstLetter","res":"t","app":"firstLetter(tokyo)"},
      {"s":"tokyo","c":"length","res":"5","app":"length(tokyo)"},
      {"s":"tokyo","c":"upper","res":"TOKYO","app":"upper(tokyo)"}
    ]
  },
  "tables": [
    {"cols":["cut"],"rows":["arc","bat","cat","lima"]},
    {"cols":["cut","firstLetter","length","upper"],"rows":["paris"]},
    {"cols":["firstLetter","length","upper"],"rows":["tokyo"]},
    {"cols":["cutWords"],"rows":["paris france"]}
  ],
  "chains": [],
  "listings": []
};
