window.GRAPH = {
  "nodes": [
    {"id":"139.69,35.68","label":"139.69,35.68","role":"value"},
    {"id":"2.35,48.85","label":"2.35,48.85","role":"value"},
    {"id":"[{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}]","label":"[{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}]","role":"value"},
    {"id":"a","label":"a","role":"value"},
    {"id":"a city is a place","label":"a city is a place","role":"value"},
    {"id":"asia","label":"asia","role":"value"},
    {"id":"a|city|is|a|place","label":"a|city|is|a|place","role":"value"},
    {"id":"bare-csv","label":"bare-csv","role":"value"},
    {"id":"block()","label":"block()","role":"function"},
    {"id":"block(name: paris\nnation: france|name: tokyo\nnation: japan,name: paris\nnation: france)","label":"block(name: paris\nnation: france|name: tokyo\nnation: japan,name: paris\nnation: france)","role":"application"},
    {"id":"block(name: paris\nnation: france|name: tokyo\nnation: japan,name: tokyo\nnation: japan)","label":"block(name: paris\nnation: france|name: tokyo\nnation: japan,name: tokyo\nnation: japan)","role":"application"},
    {"id":"city","label":"city","role":"value"},
    {"id":"city()","label":"city()","role":"function"},
    {"id":"city(paris,france)","label":"city(paris,france)","role":"application"},
    {"id":"city(tokyo,japan)","label":"city(tokyo,japan)","role":"application"},
    {"id":"city,country\nparis,france\ntokyo,japan","label":"city,country\nparis,france\ntokyo,japan","role":"value"},
    {"id":"country()","label":"country()","role":"function"},
    {"id":"country(paris,france)","label":"country(paris,france)","role":"application"},
    {"id":"country(tokyo,japan)","label":"country(tokyo,japan)","role":"application"},
    {"id":"cutBlocks()","label":"cutBlocks()","role":"function"},
    {"id":"cutBlocks(name: paris\nnation: france\n\nname: tokyo\nnation: japan)","label":"cutBlocks(name: paris\nnation: france\n\nname: tokyo\nnation: japan)","role":"application"},
    {"id":"cutFields()","label":"cutFields()","role":"function"},
    {"id":"cutFields(paris,france,europe)","label":"cutFields(paris,france,europe)","role":"application"},
    {"id":"cutFields(tokyo,japan,asia)","label":"cutFields(tokyo,japan,asia)","role":"application"},
    {"id":"cutGroupedFields()","label":"cutGroupedFields()","role":"function"},
    {"id":"cutGroupedFields(paris:2.35,48.85)","label":"cutGroupedFields(paris:2.35,48.85)","role":"application"},
    {"id":"cutGroupedFields(tokyo:139.69,35.68)","label":"cutGroupedFields(tokyo:139.69,35.68)","role":"application"},
    {"id":"cutGroupedLines()","label":"cutGroupedLines()","role":"function"},
    {"id":"cutGroupedLines(paris:2.35,48.85\ntokyo:139.69,35.68)","label":"cutGroupedLines(paris:2.35,48.85\ntokyo:139.69,35.68)","role":"application"},
    {"id":"cutItems()","label":"cutItems()","role":"function"},
    {"id":"cutItems([{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}])","label":"cutItems([{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}])","role":"application"},
    {"id":"cutLines()","label":"cutLines()","role":"function"},
    {"id":"cutLines(paris,france,europe\ntokyo,japan,asia)","label":"cutLines(paris,france,europe\ntokyo,japan,asia)","role":"application"},
    {"id":"cutPairs()","label":"cutPairs()","role":"function"},
    {"id":"cutPairs(name: paris\nnation: france)","label":"cutPairs(name: paris\nnation: france)","role":"application"},
    {"id":"cutPairs(name: tokyo\nnation: japan)","label":"cutPairs(name: tokyo\nnation: japan)","role":"application"},
    {"id":"cutParagraphs()","label":"cutParagraphs()","role":"function"},
    {"id":"cutParagraphs(paris sits on the seine\ntokyo sits on the sumida\n\na city is a place)","label":"cutParagraphs(paris sits on the seine\ntokyo sits on the sumida\n\na city is a place)","role":"application"},
    {"id":"cutRows()","label":"cutRows()","role":"function"},
    {"id":"cutRows(city,country\nparis,france\ntokyo,japan)","label":"cutRows(city,country\nparis,france\ntokyo,japan)","role":"application"},
    {"id":"cutSentences()","label":"cutSentences()","role":"function"},
    {"id":"cutSentences(a city is a place)","label":"cutSentences(a city is a place)","role":"application"},
    {"id":"cutSentences(paris sits on the seine\ntokyo sits on the sumida)","label":"cutSentences(paris sits on the seine\ntokyo sits on the sumida)","role":"application"},
    {"id":"cutWords()","label":"cutWords()","role":"function"},
    {"id":"cutWords(a city is a place)","label":"cutWords(a city is a place)","role":"application"},
    {"id":"cutWords(paris sits on the seine)","label":"cutWords(paris sits on the seine)","role":"application"},
    {"id":"cutWords(tokyo sits on the sumida)","label":"cutWords(tokyo sits on the sumida)","role":"application"},
    {"id":"europe","label":"europe","role":"value"},
    {"id":"field()","label":"field()","role":"function"},
    {"id":"field(paris|france|europe,europe)","label":"field(paris|france|europe,europe)","role":"application"},
    {"id":"field(paris|france|europe,france)","label":"field(paris|france|europe,france)","role":"application"},
    {"id":"field(paris|france|europe,paris)","label":"field(paris|france|europe,paris)","role":"application"},
    {"id":"field(tokyo|japan|asia,asia)","label":"field(tokyo|japan|asia,asia)","role":"application"},
    {"id":"field(tokyo|japan|asia,japan)","label":"field(tokyo|japan|asia,japan)","role":"application"},
    {"id":"field(tokyo|japan|asia,tokyo)","label":"field(tokyo|japan|asia,tokyo)","role":"application"},
    {"id":"france","label":"france","role":"value"},
    {"id":"grouped","label":"grouped","role":"value"},
    {"id":"groupedField()","label":"groupedField()","role":"function"},
    {"id":"groupedField(paris|2.35,48.85,2.35,48.85)","label":"groupedField(paris|2.35,48.85,2.35,48.85)","role":"application"},
    {"id":"groupedField(paris|2.35,48.85,paris)","label":"groupedField(paris|2.35,48.85,paris)","role":"application"},
    {"id":"groupedField(tokyo|139.69,35.68,139.69,35.68)","label":"groupedField(tokyo|139.69,35.68,139.69,35.68)","role":"application"},
    {"id":"groupedField(tokyo|139.69,35.68,tokyo)","label":"groupedField(tokyo|139.69,35.68,tokyo)","role":"application"},
    {"id":"groupedLine()","label":"groupedLine()","role":"function"},
    {"id":"groupedLine(paris:2.35,48.85|tokyo:139.69,35.68,paris:2.35,48.85)","label":"groupedLine(paris:2.35,48.85|tokyo:139.69,35.68,paris:2.35,48.85)","role":"application"},
    {"id":"groupedLine(paris:2.35,48.85|tokyo:139.69,35.68,tokyo:139.69,35.68)","label":"groupedLine(paris:2.35,48.85|tokyo:139.69,35.68,tokyo:139.69,35.68)","role":"application"},
    {"id":"hasFormat()","label":"hasFormat()","role":"function"},
    {"id":"hasFormat([{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}],json)","label":"hasFormat([{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}],json)","role":"application"},
    {"id":"hasFormat(city,country\nparis,france\ntokyo,japan,headered-csv)","label":"hasFormat(city,country\nparis,france\ntokyo,japan,headered-csv)","role":"application"},
    {"id":"hasFormat(name: paris\nnation: france\n\nname: tokyo\nnation: japan,key-value)","label":"hasFormat(name: paris\nnation: france\n\nname: tokyo\nnation: japan,key-value)","role":"application"},
    {"id":"hasFormat(paris sits on the seine\ntokyo sits on the sumida\n\na city is a place,prose)","label":"hasFormat(paris sits on the seine\ntokyo sits on the sumida\n\na city is a place,prose)","role":"application"},
    {"id":"hasFormat(paris,france,europe\ntokyo,japan,asia,bare-csv)","label":"hasFormat(paris,france,europe\ntokyo,japan,asia,bare-csv)","role":"application"},
    {"id":"hasFormat(paris:2.35,48.85\ntokyo:139.69,35.68,grouped)","label":"hasFormat(paris:2.35,48.85\ntokyo:139.69,35.68,grouped)","role":"application"},
    {"id":"headered-csv","label":"headered-csv","role":"value"},
    {"id":"is","label":"is","role":"value"},
    {"id":"item()","label":"item()","role":"function"},
    {"id":"item({\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"},{\"place\":\"paris\",\"river\":\"seine\"})","label":"item({\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"},{\"place\":\"paris\",\"river\":\"seine\"})","role":"application"},
    {"id":"item({\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"},{\"place\":\"tokyo\",\"river\":\"sumida\"})","label":"item({\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"},{\"place\":\"tokyo\",\"river\":\"sumida\"})","role":"application"},
    {"id":"japan","label":"japan","role":"value"},
    {"id":"json","label":"json","role":"value"},
    {"id":"key-value","label":"key-value","role":"value"},
    {"id":"line()","label":"line()","role":"function"},
    {"id":"line(paris,france,europe|tokyo,japan,asia,paris,france,europe)","label":"line(paris,france,europe|tokyo,japan,asia,paris,france,europe)","role":"application"},
    {"id":"line(paris,france,europe|tokyo,japan,asia,tokyo,japan,asia)","label":"line(paris,france,europe|tokyo,japan,asia,tokyo,japan,asia)","role":"application"},
    {"id":"name()","label":"name()","role":"function"},
    {"id":"name(name: paris)","label":"name(name: paris)","role":"application"},
    {"id":"name(name: tokyo)","label":"name(name: tokyo)","role":"application"},
    {"id":"name: paris","label":"name: paris","role":"value"},
    {"id":"name: paris\nnation: france","label":"name: paris\nnation: france","role":"value"},
    {"id":"name: paris\nnation: france\n\nname: tokyo\nnation: japan","label":"name: paris\nnation: france\n\nname: tokyo\nnation: japan","role":"value"},
    {"id":"name: paris\nnation: france|name: tokyo\nnation: japan","label":"name: paris\nnation: france|name: tokyo\nnation: japan","role":"value"},
    {"id":"name: paris|nation: france","label":"name: paris|nation: france","role":"value"},
    {"id":"name: tokyo","label":"name: tokyo","role":"value"},
    {"id":"name: tokyo\nnation: japan","label":"name: tokyo\nnation: japan","role":"value"},
    {"id":"name: tokyo|nation: japan","label":"name: tokyo|nation: japan","role":"value"},
    {"id":"nation()","label":"nation()","role":"function"},
    {"id":"nation(nation: france)","label":"nation(nation: france)","role":"application"},
    {"id":"nation(nation: japan)","label":"nation(nation: japan)","role":"application"},
    {"id":"nation: france","label":"nation: france","role":"value"},
    {"id":"nation: japan","label":"nation: japan","role":"value"},
    {"id":"on","label":"on","role":"value"},
    {"id":"pair()","label":"pair()","role":"function"},
    {"id":"pair(name: paris|nation: france,name: paris)","label":"pair(name: paris|nation: france,name: paris)","role":"application"},
    {"id":"pair(name: paris|nation: france,nation: france)","label":"pair(name: paris|nation: france,nation: france)","role":"application"},
    {"id":"pair(name: tokyo|nation: japan,name: tokyo)","label":"pair(name: tokyo|nation: japan,name: tokyo)","role":"application"},
    {"id":"pair(name: tokyo|nation: japan,nation: japan)","label":"pair(name: tokyo|nation: japan,nation: japan)","role":"application"},
    {"id":"paragraph()","label":"paragraph()","role":"function"},
    {"id":"paragraph(paris sits on the seine\ntokyo sits on the sumida|a city is a place,a city is a place)","label":"paragraph(paris sits on the seine\ntokyo sits on the sumida|a city is a place,a city is a place)","role":"application"},
    {"id":"paragraph(paris sits on the seine\ntokyo sits on the sumida|a city is a place,paris sits on the seine\ntokyo sits on the sumida)","label":"paragraph(paris sits on the seine\ntokyo sits on the sumida|a city is a place,paris sits on the seine\ntokyo sits on the sumida)","role":"application"},
    {"id":"paris","label":"paris","role":"value"},
    {"id":"paris sits on the seine","label":"paris sits on the seine","role":"value"},
    {"id":"paris sits on the seine\ntokyo sits on the sumida","label":"paris sits on the seine\ntokyo sits on the sumida","role":"value"},
    {"id":"paris sits on the seine\ntokyo sits on the sumida\n\na city is a place","label":"paris sits on the seine\ntokyo sits on the sumida\n\na city is a place","role":"value"},
    {"id":"paris sits on the seine\ntokyo sits on the sumida|a city is a place","label":"paris sits on the seine\ntokyo sits on the sumida|a city is a place","role":"value"},
    {"id":"paris sits on the seine|tokyo sits on the sumida","label":"paris sits on the seine|tokyo sits on the sumida","role":"value"},
    {"id":"paris,france","label":"paris,france","role":"value"},
    {"id":"paris,france,europe","label":"paris,france,europe","role":"value"},
    {"id":"paris,france,europe\ntokyo,japan,asia","label":"paris,france,europe\ntokyo,japan,asia","role":"value"},
    {"id":"paris,france,europe|tokyo,japan,asia","label":"paris,france,europe|tokyo,japan,asia","role":"value"},
    {"id":"paris,france|tokyo,japan","label":"paris,france|tokyo,japan","role":"value"},
    {"id":"paris:2.35,48.85","label":"paris:2.35,48.85","role":"value"},
    {"id":"paris:2.35,48.85\ntokyo:139.69,35.68","label":"paris:2.35,48.85\ntokyo:139.69,35.68","role":"value"},
    {"id":"paris:2.35,48.85|tokyo:139.69,35.68","label":"paris:2.35,48.85|tokyo:139.69,35.68","role":"value"},
    {"id":"paris|2.35,48.85","label":"paris|2.35,48.85","role":"value"},
    {"id":"paris|france|europe","label":"paris|france|europe","role":"value"},
    {"id":"paris|sits|on|the|seine","label":"paris|sits|on|the|seine","role":"value"},
    {"id":"place","label":"place","role":"value"},
    {"id":"place()","label":"place()","role":"function"},
    {"id":"place({\"place\":\"paris\",\"river\":\"seine\"})","label":"place({\"place\":\"paris\",\"river\":\"seine\"})","role":"application"},
    {"id":"place({\"place\":\"tokyo\",\"river\":\"sumida\"})","label":"place({\"place\":\"tokyo\",\"river\":\"sumida\"})","role":"application"},
    {"id":"prose","label":"prose","role":"value"},
    {"id":"river()","label":"river()","role":"function"},
    {"id":"river({\"place\":\"paris\",\"river\":\"seine\"})","label":"river({\"place\":\"paris\",\"river\":\"seine\"})","role":"application"},
    {"id":"river({\"place\":\"tokyo\",\"river\":\"sumida\"})","label":"river({\"place\":\"tokyo\",\"river\":\"sumida\"})","role":"application"},
    {"id":"row()","label":"row()","role":"function"},
    {"id":"row(paris,france|tokyo,japan,paris,france)","label":"row(paris,france|tokyo,japan,paris,france)","role":"application"},
    {"id":"row(paris,france|tokyo,japan,tokyo,japan)","label":"row(paris,france|tokyo,japan,tokyo,japan)","role":"application"},
    {"id":"seine","label":"seine","role":"value"},
    {"id":"sentence()","label":"sentence()","role":"function"},
    {"id":"sentence(a city is a place,a city is a place)","label":"sentence(a city is a place,a city is a place)","role":"application"},
    {"id":"sentence(paris sits on the seine|tokyo sits on the sumida,paris sits on the seine)","label":"sentence(paris sits on the seine|tokyo sits on the sumida,paris sits on the seine)","role":"application"},
    {"id":"sentence(paris sits on the seine|tokyo sits on the sumida,tokyo sits on the sumida)","label":"sentence(paris sits on the seine|tokyo sits on the sumida,tokyo sits on the sumida)","role":"application"},
    {"id":"sits","label":"sits","role":"value"},
    {"id":"sumida","label":"sumida","role":"value"},
    {"id":"the","label":"the","role":"value"},
    {"id":"tokyo","label":"tokyo","role":"value"},
    {"id":"tokyo sits on the sumida","label":"tokyo sits on the sumida","role":"value"},
    {"id":"tokyo,japan","label":"tokyo,japan","role":"value"},
    {"id":"tokyo,japan,asia","label":"tokyo,japan,asia","role":"value"},
    {"id":"tokyo:139.69,35.68","label":"tokyo:139.69,35.68","role":"value"},
    {"id":"tokyo|139.69,35.68","label":"tokyo|139.69,35.68","role":"value"},
    {"id":"tokyo|japan|asia","label":"tokyo|japan|asia","role":"value"},
    {"id":"tokyo|sits|on|the|sumida","label":"tokyo|sits|on|the|sumida","role":"value"},
    {"id":"word()","label":"word()","role":"function"},
    {"id":"word(a|city|is|a|place,a)","label":"word(a|city|is|a|place,a)","role":"application"},
    {"id":"word(a|city|is|a|place,city)","label":"word(a|city|is|a|place,city)","role":"application"},
    {"id":"word(a|city|is|a|place,is)","label":"word(a|city|is|a|place,is)","role":"application"},
    {"id":"word(a|city|is|a|place,place)","label":"word(a|city|is|a|place,place)","role":"application"},
    {"id":"word(paris|sits|on|the|seine,on)","label":"word(paris|sits|on|the|seine,on)","role":"application"},
    {"id":"word(paris|sits|on|the|seine,paris)","label":"word(paris|sits|on|the|seine,paris)","role":"application"},
    {"id":"word(paris|sits|on|the|seine,seine)","label":"word(paris|sits|on|the|seine,seine)","role":"application"},
    {"id":"word(paris|sits|on|the|seine,sits)","label":"word(paris|sits|on|the|seine,sits)","role":"application"},
    {"id":"word(paris|sits|on|the|seine,the)","label":"word(paris|sits|on|the|seine,the)","role":"application"},
    {"id":"word(tokyo|sits|on|the|sumida,on)","label":"word(tokyo|sits|on|the|sumida,on)","role":"application"},
    {"id":"word(tokyo|sits|on|the|sumida,sits)","label":"word(tokyo|sits|on|the|sumida,sits)","role":"application"},
    {"id":"word(tokyo|sits|on|the|sumida,sumida)","label":"word(tokyo|sits|on|the|sumida,sumida)","role":"application"},
    {"id":"word(tokyo|sits|on|the|sumida,the)","label":"word(tokyo|sits|on|the|sumida,the)","role":"application"},
    {"id":"word(tokyo|sits|on|the|sumida,tokyo)","label":"word(tokyo|sits|on|the|sumida,tokyo)","role":"application"},
    {"id":"{\"place\":\"paris\",\"river\":\"seine\"}","label":"{\"place\":\"paris\",\"river\":\"seine\"}","role":"value"},
    {"id":"{\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"}","label":"{\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"}","role":"value"},
    {"id":"{\"place\":\"tokyo\",\"river\":\"sumida\"}","label":"{\"place\":\"tokyo\",\"river\":\"sumida\"}","role":"value"}
  ],
  "edges": [
    {"from":"139.69,35.68","to":"groupedField(tokyo|139.69,35.68,139.69,35.68)"},
    {"from":"2.35,48.85","to":"groupedField(paris|2.35,48.85,2.35,48.85)"},
    {"from":"[{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}]","to":"cutItems([{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}])"},
    {"from":"[{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}]","to":"hasFormat([{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}],json)"},
    {"from":"a","to":"word(a|city|is|a|place,a)"},
    {"from":"a city is a place","to":"cutSentences(a city is a place)"},
    {"from":"a city is a place","to":"cutWords(a city is a place)"},
    {"from":"a city is a place","to":"paragraph(paris sits on the seine\ntokyo sits on the sumida|a city is a place,a city is a place)"},
    {"from":"a city is a place","to":"sentence(a city is a place,a city is a place)"},
    {"from":"asia","to":"field(tokyo|japan|asia,asia)"},
    {"from":"a|city|is|a|place","to":"word(a|city|is|a|place,a)"},
    {"from":"a|city|is|a|place","to":"word(a|city|is|a|place,city)"},
    {"from":"a|city|is|a|place","to":"word(a|city|is|a|place,is)"},
    {"from":"a|city|is|a|place","to":"word(a|city|is|a|place,place)"},
    {"from":"bare-csv","to":"hasFormat(paris,france,europe\ntokyo,japan,asia,bare-csv)"},
    {"from":"block()","to":"block(name: paris\nnation: france|name: tokyo\nnation: japan,name: paris\nnation: france)"},
    {"from":"block()","to":"block(name: paris\nnation: france|name: tokyo\nnation: japan,name: tokyo\nnation: japan)"},
    {"from":"block(name: paris\nnation: france|name: tokyo\nnation: japan,name: paris\nnation: france)","to":"name: paris\nnation: france"},
    {"from":"block(name: paris\nnation: france|name: tokyo\nnation: japan,name: tokyo\nnation: japan)","to":"name: tokyo\nnation: japan"},
    {"from":"city","to":"word(a|city|is|a|place,city)"},
    {"from":"city()","to":"city(paris,france)"},
    {"from":"city()","to":"city(tokyo,japan)"},
    {"from":"city(paris,france)","to":"paris"},
    {"from":"city(tokyo,japan)","to":"tokyo"},
    {"from":"city,country\nparis,france\ntokyo,japan","to":"cutRows(city,country\nparis,france\ntokyo,japan)"},
    {"from":"city,country\nparis,france\ntokyo,japan","to":"hasFormat(city,country\nparis,france\ntokyo,japan,headered-csv)"},
    {"from":"country()","to":"country(paris,france)"},
    {"from":"country()","to":"country(tokyo,japan)"},
    {"from":"country(paris,france)","to":"france"},
    {"from":"country(tokyo,japan)","to":"japan"},
    {"from":"cutBlocks()","to":"cutBlocks(name: paris\nnation: france\n\nname: tokyo\nnation: japan)"},
    {"from":"cutBlocks(name: paris\nnation: france\n\nname: tokyo\nnation: japan)","to":"name: paris\nnation: france|name: tokyo\nnation: japan"},
    {"from":"cutFields()","to":"cutFields(paris,france,europe)"},
    {"from":"cutFields()","to":"cutFields(tokyo,japan,asia)"},
    {"from":"cutFields(paris,france,europe)","to":"paris|france|europe"},
    {"from":"cutFields(tokyo,japan,asia)","to":"tokyo|japan|asia"},
    {"from":"cutGroupedFields()","to":"cutGroupedFields(paris:2.35,48.85)"},
    {"from":"cutGroupedFields()","to":"cutGroupedFields(tokyo:139.69,35.68)"},
    {"from":"cutGroupedFields(paris:2.35,48.85)","to":"paris|2.35,48.85"},
    {"from":"cutGroupedFields(tokyo:139.69,35.68)","to":"tokyo|139.69,35.68"},
    {"from":"cutGroupedLines()","to":"cutGroupedLines(paris:2.35,48.85\ntokyo:139.69,35.68)"},
    {"from":"cutGroupedLines(paris:2.35,48.85\ntokyo:139.69,35.68)","to":"paris:2.35,48.85|tokyo:139.69,35.68"},
    {"from":"cutItems()","to":"cutItems([{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}])"},
    {"from":"cutItems([{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}])","to":"{\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"}"},
    {"from":"cutLines()","to":"cutLines(paris,france,europe\ntokyo,japan,asia)"},
    {"from":"cutLines(paris,france,europe\ntokyo,japan,asia)","to":"paris,france,europe|tokyo,japan,asia"},
    {"from":"cutPairs()","to":"cutPairs(name: paris\nnation: france)"},
    {"from":"cutPairs()","to":"cutPairs(name: tokyo\nnation: japan)"},
    {"from":"cutPairs(name: paris\nnation: france)","to":"name: paris|nation: france"},
    {"from":"cutPairs(name: tokyo\nnation: japan)","to":"name: tokyo|nation: japan"},
    {"from":"cutParagraphs()","to":"cutParagraphs(paris sits on the seine\ntokyo sits on the sumida\n\na city is a place)"},
    {"from":"cutParagraphs(paris sits on the seine\ntokyo sits on the sumida\n\na city is a place)","to":"paris sits on the seine\ntokyo sits on the sumida|a city is a place"},
    {"from":"cutRows()","to":"cutRows(city,country\nparis,france\ntokyo,japan)"},
    {"from":"cutRows(city,country\nparis,france\ntokyo,japan)","to":"paris,france|tokyo,japan"},
    {"from":"cutSentences()","to":"cutSentences(a city is a place)"},
    {"from":"cutSentences()","to":"cutSentences(paris sits on the seine\ntokyo sits on the sumida)"},
    {"from":"cutSentences(a city is a place)","to":"a city is a place"},
    {"from":"cutSentences(paris sits on the seine\ntokyo sits on the sumida)","to":"paris sits on the seine|tokyo sits on the sumida"},
    {"from":"cutWords()","to":"cutWords(a city is a place)"},
    {"from":"cutWords()","to":"cutWords(paris sits on the seine)"},
    {"from":"cutWords()","to":"cutWords(tokyo sits on the sumida)"},
    {"from":"cutWords(a city is a place)","to":"a|city|is|a|place"},
    {"from":"cutWords(paris sits on the seine)","to":"paris|sits|on|the|seine"},
    {"from":"cutWords(tokyo sits on the sumida)","to":"tokyo|sits|on|the|sumida"},
    {"from":"europe","to":"field(paris|france|europe,europe)"},
    {"from":"field()","to":"field(paris|france|europe,europe)"},
    {"from":"field()","to":"field(paris|france|europe,france)"},
    {"from":"field()","to":"field(paris|france|europe,paris)"},
    {"from":"field()","to":"field(tokyo|japan|asia,asia)"},
    {"from":"field()","to":"field(tokyo|japan|asia,japan)"},
    {"from":"field()","to":"field(tokyo|japan|asia,tokyo)"},
    {"from":"field(paris|france|europe,europe)","to":"europe"},
    {"from":"field(paris|france|europe,france)","to":"france"},
    {"from":"field(paris|france|europe,paris)","to":"paris"},
    {"from":"field(tokyo|japan|asia,asia)","to":"asia"},
    {"from":"field(tokyo|japan|asia,japan)","to":"japan"},
    {"from":"field(tokyo|japan|asia,tokyo)","to":"tokyo"},
    {"from":"france","to":"field(paris|france|europe,france)"},
    {"from":"grouped","to":"hasFormat(paris:2.35,48.85\ntokyo:139.69,35.68,grouped)"},
    {"from":"groupedField()","to":"groupedField(paris|2.35,48.85,2.35,48.85)"},
    {"from":"groupedField()","to":"groupedField(paris|2.35,48.85,paris)"},
    {"from":"groupedField()","to":"groupedField(tokyo|139.69,35.68,139.69,35.68)"},
    {"from":"groupedField()","to":"groupedField(tokyo|139.69,35.68,tokyo)"},
    {"from":"groupedField(paris|2.35,48.85,2.35,48.85)","to":"2.35,48.85"},
    {"from":"groupedField(paris|2.35,48.85,paris)","to":"paris"},
    {"from":"groupedField(tokyo|139.69,35.68,139.69,35.68)","to":"139.69,35.68"},
    {"from":"groupedField(tokyo|139.69,35.68,tokyo)","to":"tokyo"},
    {"from":"groupedLine()","to":"groupedLine(paris:2.35,48.85|tokyo:139.69,35.68,paris:2.35,48.85)"},
    {"from":"groupedLine()","to":"groupedLine(paris:2.35,48.85|tokyo:139.69,35.68,tokyo:139.69,35.68)"},
    {"from":"groupedLine(paris:2.35,48.85|tokyo:139.69,35.68,paris:2.35,48.85)","to":"paris:2.35,48.85"},
    {"from":"groupedLine(paris:2.35,48.85|tokyo:139.69,35.68,tokyo:139.69,35.68)","to":"tokyo:139.69,35.68"},
    {"from":"hasFormat()","to":"hasFormat([{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}],json)"},
    {"from":"hasFormat()","to":"hasFormat(city,country\nparis,france\ntokyo,japan,headered-csv)"},
    {"from":"hasFormat()","to":"hasFormat(name: paris\nnation: france\n\nname: tokyo\nnation: japan,key-value)"},
    {"from":"hasFormat()","to":"hasFormat(paris sits on the seine\ntokyo sits on the sumida\n\na city is a place,prose)"},
    {"from":"hasFormat()","to":"hasFormat(paris,france,europe\ntokyo,japan,asia,bare-csv)"},
    {"from":"hasFormat()","to":"hasFormat(paris:2.35,48.85\ntokyo:139.69,35.68,grouped)"},
    {"from":"hasFormat([{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}],json)","to":"json"},
    {"from":"hasFormat(city,country\nparis,france\ntokyo,japan,headered-csv)","to":"headered-csv"},
    {"from":"hasFormat(name: paris\nnation: france\n\nname: tokyo\nnation: japan,key-value)","to":"key-value"},
    {"from":"hasFormat(paris sits on the seine\ntokyo sits on the sumida\n\na city is a place,prose)","to":"prose"},
    {"from":"hasFormat(paris,france,europe\ntokyo,japan,asia,bare-csv)","to":"bare-csv"},
    {"from":"hasFormat(paris:2.35,48.85\ntokyo:139.69,35.68,grouped)","to":"grouped"},
    {"from":"headered-csv","to":"hasFormat(city,country\nparis,france\ntokyo,japan,headered-csv)"},
    {"from":"is","to":"word(a|city|is|a|place,is)"},
    {"from":"item()","to":"item({\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"},{\"place\":\"paris\",\"river\":\"seine\"})"},
    {"from":"item()","to":"item({\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"},{\"place\":\"tokyo\",\"river\":\"sumida\"})"},
    {"from":"item({\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"},{\"place\":\"paris\",\"river\":\"seine\"})","to":"{\"place\":\"paris\",\"river\":\"seine\"}"},
    {"from":"item({\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"},{\"place\":\"tokyo\",\"river\":\"sumida\"})","to":"{\"place\":\"tokyo\",\"river\":\"sumida\"}"},
    {"from":"japan","to":"field(tokyo|japan|asia,japan)"},
    {"from":"json","to":"hasFormat([{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}],json)"},
    {"from":"key-value","to":"hasFormat(name: paris\nnation: france\n\nname: tokyo\nnation: japan,key-value)"},
    {"from":"line()","to":"line(paris,france,europe|tokyo,japan,asia,paris,france,europe)"},
    {"from":"line()","to":"line(paris,france,europe|tokyo,japan,asia,tokyo,japan,asia)"},
    {"from":"line(paris,france,europe|tokyo,japan,asia,paris,france,europe)","to":"paris,france,europe"},
    {"from":"line(paris,france,europe|tokyo,japan,asia,tokyo,japan,asia)","to":"tokyo,japan,asia"},
    {"from":"name()","to":"name(name: paris)"},
    {"from":"name()","to":"name(name: tokyo)"},
    {"from":"name(name: paris)","to":"paris"},
    {"from":"name(name: tokyo)","to":"tokyo"},
    {"from":"name: paris","to":"name(name: paris)"},
    {"from":"name: paris","to":"pair(name: paris|nation: france,name: paris)"},
    {"from":"name: paris\nnation: france","to":"block(name: paris\nnation: france|name: tokyo\nnation: japan,name: paris\nnation: france)"},
    {"from":"name: paris\nnation: france","to":"cutPairs(name: paris\nnation: france)"},
    {"from":"name: paris\nnation: france\n\nname: tokyo\nnation: japan","to":"cutBlocks(name: paris\nnation: france\n\nname: tokyo\nnation: japan)"},
    {"from":"name: paris\nnation: france\n\nname: tokyo\nnation: japan","to":"hasFormat(name: paris\nnation: france\n\nname: tokyo\nnation: japan,key-value)"},
    {"from":"name: paris\nnation: france|name: tokyo\nnation: japan","to":"block(name: paris\nnation: france|name: tokyo\nnation: japan,name: paris\nnation: france)"},
    {"from":"name: paris\nnation: france|name: tokyo\nnation: japan","to":"block(name: paris\nnation: france|name: tokyo\nnation: japan,name: tokyo\nnation: japan)"},
    {"from":"name: paris|nation: france","to":"pair(name: paris|nation: france,name: paris)"},
    {"from":"name: paris|nation: france","to":"pair(name: paris|nation: france,nation: france)"},
    {"from":"name: tokyo","to":"name(name: tokyo)"},
    {"from":"name: tokyo","to":"pair(name: tokyo|nation: japan,name: tokyo)"},
    {"from":"name: tokyo\nnation: japan","to":"block(name: paris\nnation: france|name: tokyo\nnation: japan,name: tokyo\nnation: japan)"},
    {"from":"name: tokyo\nnation: japan","to":"cutPairs(name: tokyo\nnation: japan)"},
    {"from":"name: tokyo|nation: japan","to":"pair(name: tokyo|nation: japan,name: tokyo)"},
    {"from":"name: tokyo|nation: japan","to":"pair(name: tokyo|nation: japan,nation: japan)"},
    {"from":"nation()","to":"nation(nation: france)"},
    {"from":"nation()","to":"nation(nation: japan)"},
    {"from":"nation(nation: france)","to":"france"},
    {"from":"nation(nation: japan)","to":"japan"},
    {"from":"nation: france","to":"nation(nation: france)"},
    {"from":"nation: france","to":"pair(name: paris|nation: france,nation: france)"},
    {"from":"nation: japan","to":"nation(nation: japan)"},
    {"from":"nation: japan","to":"pair(name: tokyo|nation: japan,nation: japan)"},
    {"from":"on","to":"word(paris|sits|on|the|seine,on)"},
    {"from":"on","to":"word(tokyo|sits|on|the|sumida,on)"},
    {"from":"pair()","to":"pair(name: paris|nation: france,name: paris)"},
    {"from":"pair()","to":"pair(name: paris|nation: france,nation: france)"},
    {"from":"pair()","to":"pair(name: tokyo|nation: japan,name: tokyo)"},
    {"from":"pair()","to":"pair(name: tokyo|nation: japan,nation: japan)"},
    {"from":"pair(name: paris|nation: france,name: paris)","to":"name: paris"},
    {"from":"pair(name: paris|nation: france,nation: france)","to":"nation: france"},
    {"from":"pair(name: tokyo|nation: japan,name: tokyo)","to":"name: tokyo"},
    {"from":"pair(name: tokyo|nation: japan,nation: japan)","to":"nation: japan"},
    {"from":"paragraph()","to":"paragraph(paris sits on the seine\ntokyo sits on the sumida|a city is a place,a city is a place)"},
    {"from":"paragraph()","to":"paragraph(paris sits on the seine\ntokyo sits on the sumida|a city is a place,paris sits on the seine\ntokyo sits on the sumida)"},
    {"from":"paragraph(paris sits on the seine\ntokyo sits on the sumida|a city is a place,a city is a place)","to":"a city is a place"},
    {"from":"paragraph(paris sits on the seine\ntokyo sits on the sumida|a city is a place,paris sits on the seine\ntokyo sits on the sumida)","to":"paris sits on the seine\ntokyo sits on the sumida"},
    {"from":"paris","to":"field(paris|france|europe,paris)"},
    {"from":"paris","to":"groupedField(paris|2.35,48.85,paris)"},
    {"from":"paris","to":"word(paris|sits|on|the|seine,paris)"},
    {"from":"paris sits on the seine","to":"cutWords(paris sits on the seine)"},
    {"from":"paris sits on the seine","to":"sentence(paris sits on the seine|tokyo sits on the sumida,paris sits on the seine)"},
    {"from":"paris sits on the seine\ntokyo sits on the sumida","to":"cutSentences(paris sits on the seine\ntokyo sits on the sumida)"},
    {"from":"paris sits on the seine\ntokyo sits on the sumida","to":"paragraph(paris sits on the seine\ntokyo sits on the sumida|a city is a place,paris sits on the seine\ntokyo sits on the sumida)"},
    {"from":"paris sits on the seine\ntokyo sits on the sumida\n\na city is a place","to":"cutParagraphs(paris sits on the seine\ntokyo sits on the sumida\n\na city is a place)"},
    {"from":"paris sits on the seine\ntokyo sits on the sumida\n\na city is a place","to":"hasFormat(paris sits on the seine\ntokyo sits on the sumida\n\na city is a place,prose)"},
    {"from":"paris sits on the seine\ntokyo sits on the sumida|a city is a place","to":"paragraph(paris sits on the seine\ntokyo sits on the sumida|a city is a place,a city is a place)"},
    {"from":"paris sits on the seine\ntokyo sits on the sumida|a city is a place","to":"paragraph(paris sits on the seine\ntokyo sits on the sumida|a city is a place,paris sits on the seine\ntokyo sits on the sumida)"},
    {"from":"paris sits on the seine|tokyo sits on the sumida","to":"sentence(paris sits on the seine|tokyo sits on the sumida,paris sits on the seine)"},
    {"from":"paris sits on the seine|tokyo sits on the sumida","to":"sentence(paris sits on the seine|tokyo sits on the sumida,tokyo sits on the sumida)"},
    {"from":"paris,france","to":"city(paris,france)"},
    {"from":"paris,france","to":"country(paris,france)"},
    {"from":"paris,france","to":"row(paris,france|tokyo,japan,paris,france)"},
    {"from":"paris,france,europe","to":"cutFields(paris,france,europe)"},
    {"from":"paris,france,europe","to":"line(paris,france,europe|tokyo,japan,asia,paris,france,europe)"},
    {"from":"paris,france,europe\ntokyo,japan,asia","to":"cutLines(paris,france,europe\ntokyo,japan,asia)"},
    {"from":"paris,france,europe\ntokyo,japan,asia","to":"hasFormat(paris,france,europe\ntokyo,japan,asia,bare-csv)"},
    {"from":"paris,france,europe|tokyo,japan,asia","to":"line(paris,france,europe|tokyo,japan,asia,paris,france,europe)"},
    {"from":"paris,france,europe|tokyo,japan,asia","to":"line(paris,france,europe|tokyo,japan,asia,tokyo,japan,asia)"},
    {"from":"paris,france|tokyo,japan","to":"row(paris,france|tokyo,japan,paris,france)"},
    {"from":"paris,france|tokyo,japan","to":"row(paris,france|tokyo,japan,tokyo,japan)"},
    {"from":"paris:2.35,48.85","to":"cutGroupedFields(paris:2.35,48.85)"},
    {"from":"paris:2.35,48.85","to":"groupedLine(paris:2.35,48.85|tokyo:139.69,35.68,paris:2.35,48.85)"},
    {"from":"paris:2.35,48.85\ntokyo:139.69,35.68","to":"cutGroupedLines(paris:2.35,48.85\ntokyo:139.69,35.68)"},
    {"from":"paris:2.35,48.85\ntokyo:139.69,35.68","to":"hasFormat(paris:2.35,48.85\ntokyo:139.69,35.68,grouped)"},
    {"from":"paris:2.35,48.85|tokyo:139.69,35.68","to":"groupedLine(paris:2.35,48.85|tokyo:139.69,35.68,paris:2.35,48.85)"},
    {"from":"paris:2.35,48.85|tokyo:139.69,35.68","to":"groupedLine(paris:2.35,48.85|tokyo:139.69,35.68,tokyo:139.69,35.68)"},
    {"from":"paris|2.35,48.85","to":"groupedField(paris|2.35,48.85,2.35,48.85)"},
    {"from":"paris|2.35,48.85","to":"groupedField(paris|2.35,48.85,paris)"},
    {"from":"paris|france|europe","to":"field(paris|france|europe,europe)"},
    {"from":"paris|france|europe","to":"field(paris|france|europe,france)"},
    {"from":"paris|france|europe","to":"field(paris|france|europe,paris)"},
    {"from":"paris|sits|on|the|seine","to":"word(paris|sits|on|the|seine,on)"},
    {"from":"paris|sits|on|the|seine","to":"word(paris|sits|on|the|seine,paris)"},
    {"from":"paris|sits|on|the|seine","to":"word(paris|sits|on|the|seine,seine)"},
    {"from":"paris|sits|on|the|seine","to":"word(paris|sits|on|the|seine,sits)"},
    {"from":"paris|sits|on|the|seine","to":"word(paris|sits|on|the|seine,the)"},
    {"from":"place","to":"word(a|city|is|a|place,place)"},
    {"from":"place()","to":"place({\"place\":\"paris\",\"river\":\"seine\"})"},
    {"from":"place()","to":"place({\"place\":\"tokyo\",\"river\":\"sumida\"})"},
    {"from":"place({\"place\":\"paris\",\"river\":\"seine\"})","to":"paris"},
    {"from":"place({\"place\":\"tokyo\",\"river\":\"sumida\"})","to":"tokyo"},
    {"from":"prose","to":"hasFormat(paris sits on the seine\ntokyo sits on the sumida\n\na city is a place,prose)"},
    {"from":"river()","to":"river({\"place\":\"paris\",\"river\":\"seine\"})"},
    {"from":"river()","to":"river({\"place\":\"tokyo\",\"river\":\"sumida\"})"},
    {"from":"river({\"place\":\"paris\",\"river\":\"seine\"})","to":"seine"},
    {"from":"river({\"place\":\"tokyo\",\"river\":\"sumida\"})","to":"sumida"},
    {"from":"row()","to":"row(paris,france|tokyo,japan,paris,france)"},
    {"from":"row()","to":"row(paris,france|tokyo,japan,tokyo,japan)"},
    {"from":"row(paris,france|tokyo,japan,paris,france)","to":"paris,france"},
    {"from":"row(paris,france|tokyo,japan,tokyo,japan)","to":"tokyo,japan"},
    {"from":"seine","to":"word(paris|sits|on|the|seine,seine)"},
    {"from":"sentence()","to":"sentence(a city is a place,a city is a place)"},
    {"from":"sentence()","to":"sentence(paris sits on the seine|tokyo sits on the sumida,paris sits on the seine)"},
    {"from":"sentence()","to":"sentence(paris sits on the seine|tokyo sits on the sumida,tokyo sits on the sumida)"},
    {"from":"sentence(a city is a place,a city is a place)","to":"a city is a place"},
    {"from":"sentence(paris sits on the seine|tokyo sits on the sumida,paris sits on the seine)","to":"paris sits on the seine"},
    {"from":"sentence(paris sits on the seine|tokyo sits on the sumida,tokyo sits on the sumida)","to":"tokyo sits on the sumida"},
    {"from":"sits","to":"word(paris|sits|on|the|seine,sits)"},
    {"from":"sits","to":"word(tokyo|sits|on|the|sumida,sits)"},
    {"from":"sumida","to":"word(tokyo|sits|on|the|sumida,sumida)"},
    {"from":"the","to":"word(paris|sits|on|the|seine,the)"},
    {"from":"the","to":"word(tokyo|sits|on|the|sumida,the)"},
    {"from":"tokyo","to":"field(tokyo|japan|asia,tokyo)"},
    {"from":"tokyo","to":"groupedField(tokyo|139.69,35.68,tokyo)"},
    {"from":"tokyo","to":"word(tokyo|sits|on|the|sumida,tokyo)"},
    {"from":"tokyo sits on the sumida","to":"cutWords(tokyo sits on the sumida)"},
    {"from":"tokyo sits on the sumida","to":"sentence(paris sits on the seine|tokyo sits on the sumida,tokyo sits on the sumida)"},
    {"from":"tokyo,japan","to":"city(tokyo,japan)"},
    {"from":"tokyo,japan","to":"country(tokyo,japan)"},
    {"from":"tokyo,japan","to":"row(paris,france|tokyo,japan,tokyo,japan)"},
    {"from":"tokyo,japan,asia","to":"cutFields(tokyo,japan,asia)"},
    {"from":"tokyo,japan,asia","to":"line(paris,france,europe|tokyo,japan,asia,tokyo,japan,asia)"},
    {"from":"tokyo:139.69,35.68","to":"cutGroupedFields(tokyo:139.69,35.68)"},
    {"from":"tokyo:139.69,35.68","to":"groupedLine(paris:2.35,48.85|tokyo:139.69,35.68,tokyo:139.69,35.68)"},
    {"from":"tokyo|139.69,35.68","to":"groupedField(tokyo|139.69,35.68,139.69,35.68)"},
    {"from":"tokyo|139.69,35.68","to":"groupedField(tokyo|139.69,35.68,tokyo)"},
    {"from":"tokyo|japan|asia","to":"field(tokyo|japan|asia,asia)"},
    {"from":"tokyo|japan|asia","to":"field(tokyo|japan|asia,japan)"},
    {"from":"tokyo|japan|asia","to":"field(tokyo|japan|asia,tokyo)"},
    {"from":"tokyo|sits|on|the|sumida","to":"word(tokyo|sits|on|the|sumida,on)"},
    {"from":"tokyo|sits|on|the|sumida","to":"word(tokyo|sits|on|the|sumida,sits)"},
    {"from":"tokyo|sits|on|the|sumida","to":"word(tokyo|sits|on|the|sumida,sumida)"},
    {"from":"tokyo|sits|on|the|sumida","to":"word(tokyo|sits|on|the|sumida,the)"},
    {"from":"tokyo|sits|on|the|sumida","to":"word(tokyo|sits|on|the|sumida,tokyo)"},
    {"from":"word()","to":"word(a|city|is|a|place,a)"},
    {"from":"word()","to":"word(a|city|is|a|place,city)"},
    {"from":"word()","to":"word(a|city|is|a|place,is)"},
    {"from":"word()","to":"word(a|city|is|a|place,place)"},
    {"from":"word()","to":"word(paris|sits|on|the|seine,on)"},
    {"from":"word()","to":"word(paris|sits|on|the|seine,paris)"},
    {"from":"word()","to":"word(paris|sits|on|the|seine,seine)"},
    {"from":"word()","to":"word(paris|sits|on|the|seine,sits)"},
    {"from":"word()","to":"word(paris|sits|on|the|seine,the)"},
    {"from":"word()","to":"word(tokyo|sits|on|the|sumida,on)"},
    {"from":"word()","to":"word(tokyo|sits|on|the|sumida,sits)"},
    {"from":"word()","to":"word(tokyo|sits|on|the|sumida,sumida)"},
    {"from":"word()","to":"word(tokyo|sits|on|the|sumida,the)"},
    {"from":"word()","to":"word(tokyo|sits|on|the|sumida,tokyo)"},
    {"from":"word(a|city|is|a|place,a)","to":"a"},
    {"from":"word(a|city|is|a|place,city)","to":"city"},
    {"from":"word(a|city|is|a|place,is)","to":"is"},
    {"from":"word(a|city|is|a|place,place)","to":"place"},
    {"from":"word(paris|sits|on|the|seine,on)","to":"on"},
    {"from":"word(paris|sits|on|the|seine,paris)","to":"paris"},
    {"from":"word(paris|sits|on|the|seine,seine)","to":"seine"},
    {"from":"word(paris|sits|on|the|seine,sits)","to":"sits"},
    {"from":"word(paris|sits|on|the|seine,the)","to":"the"},
    {"from":"word(tokyo|sits|on|the|sumida,on)","to":"on"},
    {"from":"word(tokyo|sits|on|the|sumida,sits)","to":"sits"},
    {"from":"word(tokyo|sits|on|the|sumida,sumida)","to":"sumida"},
    {"from":"word(tokyo|sits|on|the|sumida,the)","to":"the"},
    {"from":"word(tokyo|sits|on|the|sumida,tokyo)","to":"tokyo"},
    {"from":"{\"place\":\"paris\",\"river\":\"seine\"}","to":"item({\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"},{\"place\":\"paris\",\"river\":\"seine\"})"},
    {"from":"{\"place\":\"paris\",\"river\":\"seine\"}","to":"place({\"place\":\"paris\",\"river\":\"seine\"})"},
    {"from":"{\"place\":\"paris\",\"river\":\"seine\"}","to":"river({\"place\":\"paris\",\"river\":\"seine\"})"},
    {"from":"{\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"}","to":"item({\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"},{\"place\":\"paris\",\"river\":\"seine\"})"},
    {"from":"{\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"}","to":"item({\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"},{\"place\":\"tokyo\",\"river\":\"sumida\"})"},
    {"from":"{\"place\":\"tokyo\",\"river\":\"sumida\"}","to":"item({\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"},{\"place\":\"tokyo\",\"river\":\"sumida\"})"},
    {"from":"{\"place\":\"tokyo\",\"river\":\"sumida\"}","to":"place({\"place\":\"tokyo\",\"river\":\"sumida\"})"},
    {"from":"{\"place\":\"tokyo\",\"river\":\"sumida\"}","to":"river({\"place\":\"tokyo\",\"river\":\"sumida\"})"}
  ],
  "pivot": {
    "subjects": [
      "[{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}]",
      "a city is a place",
      "a|city|is|a|place",
      "city,country\nparis,france\ntokyo,japan",
      "name: paris",
      "name: paris\nnation: france",
      "name: paris\nnation: france\n\nname: tokyo\nnation: japan",
      "name: paris\nnation: france|name: tokyo\nnation: japan",
      "name: paris|nation: france",
      "name: tokyo",
      "name: tokyo\nnation: japan",
      "name: tokyo|nation: japan",
      "nation: france",
      "nation: japan",
      "paris sits on the seine",
      "paris sits on the seine\ntokyo sits on the sumida",
      "paris sits on the seine\ntokyo sits on the sumida\n\na city is a place",
      "paris sits on the seine\ntokyo sits on the sumida|a city is a place",
      "paris sits on the seine|tokyo sits on the sumida",
      "paris,france",
      "paris,france,europe",
      "paris,france,europe\ntokyo,japan,asia",
      "paris,france,europe|tokyo,japan,asia",
      "paris,france|tokyo,japan",
      "paris:2.35,48.85",
      "paris:2.35,48.85\ntokyo:139.69,35.68",
      "paris:2.35,48.85|tokyo:139.69,35.68",
      "paris|2.35,48.85",
      "paris|france|europe",
      "paris|sits|on|the|seine",
      "tokyo sits on the sumida",
      "tokyo,japan",
      "tokyo,japan,asia",
      "tokyo:139.69,35.68",
      "tokyo|139.69,35.68",
      "tokyo|japan|asia",
      "tokyo|sits|on|the|sumida",
      "{\"place\":\"paris\",\"river\":\"seine\"}",
      "{\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"}",
      "{\"place\":\"tokyo\",\"river\":\"sumida\"}"
    ],
    "columns": [
      "block(·,name: paris\nnation: france)",
      "block(·,name: tokyo\nnation: japan)",
      "city",
      "country",
      "cutBlocks",
      "cutFields",
      "cutGroupedFields",
      "cutGroupedLines",
      "cutItems",
      "cutLines",
      "cutPairs",
      "cutParagraphs",
      "cutRows",
      "cutSentences",
      "cutWords",
      "field(·,asia)",
      "field(·,europe)",
      "field(·,france)",
      "field(·,japan)",
      "field(·,paris)",
      "field(·,tokyo)",
      "groupedField(·,139.69,35.68)",
      "groupedField(·,2.35,48.85)",
      "groupedField(·,paris)",
      "groupedField(·,tokyo)",
      "groupedLine(·,paris:2.35,48.85)",
      "groupedLine(·,tokyo:139.69,35.68)",
      "hasFormat(·,bare-csv)",
      "hasFormat(·,grouped)",
      "hasFormat(·,headered-csv)",
      "hasFormat(·,json)",
      "hasFormat(·,key-value)",
      "hasFormat(·,prose)",
      "item(·,{\"place\":\"paris\",\"river\":\"seine\"})",
      "item(·,{\"place\":\"tokyo\",\"river\":\"sumida\"})",
      "line(·,paris,france,europe)",
      "line(·,tokyo,japan,asia)",
      "name",
      "nation",
      "pair(·,name: paris)",
      "pair(·,name: tokyo)",
      "pair(·,nation: france)",
      "pair(·,nation: japan)",
      "paragraph(·,a city is a place)",
      "paragraph(·,paris sits on the seine\ntokyo sits on the sumida)",
      "place",
      "river",
      "row(·,paris,france)",
      "row(·,tokyo,japan)",
      "sentence",
      "sentence(·,paris sits on the seine)",
      "sentence(·,tokyo sits on the sumida)",
      "word(·,a)",
      "word(·,city)",
      "word(·,is)",
      "word(·,on)",
      "word(·,paris)",
      "word(·,place)",
      "word(·,seine)",
      "word(·,sits)",
      "word(·,sumida)",
      "word(·,the)",
      "word(·,tokyo)"
    ],
    "cells": [
      {"s":"[{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}]","c":"cutItems","res":"{\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"}","app":"cutItems([{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}])"},
      {"s":"[{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}]","c":"hasFormat(·,json)","res":"json","app":"hasFormat([{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}],json)"},
      {"s":"{\"place\":\"paris\",\"river\":\"seine\"}","c":"place","res":"paris","app":"place({\"place\":\"paris\",\"river\":\"seine\"})"},
      {"s":"{\"place\":\"paris\",\"river\":\"seine\"}","c":"river","res":"seine","app":"river({\"place\":\"paris\",\"river\":\"seine\"})"},
      {"s":"{\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"}","c":"item(·,{\"place\":\"paris\",\"river\":\"seine\"})","res":"{\"place\":\"paris\",\"river\":\"seine\"}","app":"item({\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"},{\"place\":\"paris\",\"river\":\"seine\"})"},
      {"s":"{\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"}","c":"item(·,{\"place\":\"tokyo\",\"river\":\"sumida\"})","res":"{\"place\":\"tokyo\",\"river\":\"sumida\"}","app":"item({\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"},{\"place\":\"tokyo\",\"river\":\"sumida\"})"},
      {"s":"{\"place\":\"tokyo\",\"river\":\"sumida\"}","c":"place","res":"tokyo","app":"place({\"place\":\"tokyo\",\"river\":\"sumida\"})"},
      {"s":"{\"place\":\"tokyo\",\"river\":\"sumida\"}","c":"river","res":"sumida","app":"river({\"place\":\"tokyo\",\"river\":\"sumida\"})"},
      {"s":"a city is a place","c":"cutSentences","res":"a city is a place","app":"cutSentences(a city is a place)"},
      {"s":"a city is a place","c":"cutWords","res":"a|city|is|a|place","app":"cutWords(a city is a place)"},
      {"s":"a city is a place","c":"sentence","res":"a city is a place","app":"sentence(a city is a place,a city is a place)"},
      {"s":"a|city|is|a|place","c":"word(·,a)","res":"a","app":"word(a|city|is|a|place,a)"},
      {"s":"a|city|is|a|place","c":"word(·,city)","res":"city","app":"word(a|city|is|a|place,city)"},
      {"s":"a|city|is|a|place","c":"word(·,is)","res":"is","app":"word(a|city|is|a|place,is)"},
      {"s":"a|city|is|a|place","c":"word(·,place)","res":"place","app":"word(a|city|is|a|place,place)"},
      {"s":"city,country\nparis,france\ntokyo,japan","c":"cutRows","res":"paris,france|tokyo,japan","app":"cutRows(city,country\nparis,france\ntokyo,japan)"},
      {"s":"city,country\nparis,france\ntokyo,japan","c":"hasFormat(·,headered-csv)","res":"headered-csv","app":"hasFormat(city,country\nparis,france\ntokyo,japan,headered-csv)"},
      {"s":"name: paris","c":"name","res":"paris","app":"name(name: paris)"},
      {"s":"name: paris\nnation: france","c":"cutPairs","res":"name: paris|nation: france","app":"cutPairs(name: paris\nnation: france)"},
      {"s":"name: paris\nnation: france\n\nname: tokyo\nnation: japan","c":"cutBlocks","res":"name: paris\nnation: france|name: tokyo\nnation: japan","app":"cutBlocks(name: paris\nnation: france\n\nname: tokyo\nnation: japan)"},
      {"s":"name: paris\nnation: france\n\nname: tokyo\nnation: japan","c":"hasFormat(·,key-value)","res":"key-value","app":"hasFormat(name: paris\nnation: france\n\nname: tokyo\nnation: japan,key-value)"},
      {"s":"name: paris\nnation: france|name: tokyo\nnation: japan","c":"block(·,name: paris\nnation: france)","res":"name: paris\nnation: france","app":"block(name: paris\nnation: france|name: tokyo\nnation: japan,name: paris\nnation: france)"},
      {"s":"name: paris\nnation: france|name: tokyo\nnation: japan","c":"block(·,name: tokyo\nnation: japan)","res":"name: tokyo\nnation: japan","app":"block(name: paris\nnation: france|name: tokyo\nnation: japan,name: tokyo\nnation: japan)"},
      {"s":"name: paris|nation: france","c":"pair(·,name: paris)","res":"name: paris","app":"pair(name: paris|nation: france,name: paris)"},
      {"s":"name: paris|nation: france","c":"pair(·,nation: france)","res":"nation: france","app":"pair(name: paris|nation: france,nation: france)"},
      {"s":"name: tokyo","c":"name","res":"tokyo","app":"name(name: tokyo)"},
      {"s":"name: tokyo\nnation: japan","c":"cutPairs","res":"name: tokyo|nation: japan","app":"cutPairs(name: tokyo\nnation: japan)"},
      {"s":"name: tokyo|nation: japan","c":"pair(·,name: tokyo)","res":"name: tokyo","app":"pair(name: tokyo|nation: japan,name: tokyo)"},
      {"s":"name: tokyo|nation: japan","c":"pair(·,nation: japan)","res":"nation: japan","app":"pair(name: tokyo|nation: japan,nation: japan)"},
      {"s":"nation: france","c":"nation","res":"france","app":"nation(nation: france)"},
      {"s":"nation: japan","c":"nation","res":"japan","app":"nation(nation: japan)"},
      {"s":"paris sits on the seine","c":"cutWords","res":"paris|sits|on|the|seine","app":"cutWords(paris sits on the seine)"},
      {"s":"paris sits on the seine\ntokyo sits on the sumida","c":"cutSentences","res":"paris sits on the seine|tokyo sits on the sumida","app":"cutSentences(paris sits on the seine\ntokyo sits on the sumida)"},
      {"s":"paris sits on the seine\ntokyo sits on the sumida\n\na city is a place","c":"cutParagraphs","res":"paris sits on the seine\ntokyo sits on the sumida|a city is a place","app":"cutParagraphs(paris sits on the seine\ntokyo sits on the sumida\n\na city is a place)"},
      {"s":"paris sits on the seine\ntokyo sits on the sumida\n\na city is a place","c":"hasFormat(·,prose)","res":"prose","app":"hasFormat(paris sits on the seine\ntokyo sits on the sumida\n\na city is a place,prose)"},
      {"s":"paris sits on the seine\ntokyo sits on the sumida|a city is a place","c":"paragraph(·,a city is a place)","res":"a city is a place","app":"paragraph(paris sits on the seine\ntokyo sits on the sumida|a city is a place,a city is a place)"},
      {"s":"paris sits on the seine\ntokyo sits on the sumida|a city is a place","c":"paragraph(·,paris sits on the seine\ntokyo sits on the sumida)","res":"paris sits on the seine\ntokyo sits on the sumida","app":"paragraph(paris sits on the seine\ntokyo sits on the sumida|a city is a place,paris sits on the seine\ntokyo sits on the sumida)"},
      {"s":"paris sits on the seine|tokyo sits on the sumida","c":"sentence(·,paris sits on the seine)","res":"paris sits on the seine","app":"sentence(paris sits on the seine|tokyo sits on the sumida,paris sits on the seine)"},
      {"s":"paris sits on the seine|tokyo sits on the sumida","c":"sentence(·,tokyo sits on the sumida)","res":"tokyo sits on the sumida","app":"sentence(paris sits on the seine|tokyo sits on the sumida,tokyo sits on the sumida)"},
      {"s":"paris,france","c":"city","res":"paris","app":"city(paris,france)"},
      {"s":"paris,france","c":"country","res":"france","app":"country(paris,france)"},
      {"s":"paris,france,europe","c":"cutFields","res":"paris|france|europe","app":"cutFields(paris,france,europe)"},
      {"s":"paris,france,europe\ntokyo,japan,asia","c":"cutLines","res":"paris,france,europe|tokyo,japan,asia","app":"cutLines(paris,france,europe\ntokyo,japan,asia)"},
      {"s":"paris,france,europe\ntokyo,japan,asia","c":"hasFormat(·,bare-csv)","res":"bare-csv","app":"hasFormat(paris,france,europe\ntokyo,japan,asia,bare-csv)"},
      {"s":"paris,france,europe|tokyo,japan,asia","c":"line(·,paris,france,europe)","res":"paris,france,europe","app":"line(paris,france,europe|tokyo,japan,asia,paris,france,europe)"},
      {"s":"paris,france,europe|tokyo,japan,asia","c":"line(·,tokyo,japan,asia)","res":"tokyo,japan,asia","app":"line(paris,france,europe|tokyo,japan,asia,tokyo,japan,asia)"},
      {"s":"paris,france|tokyo,japan","c":"row(·,paris,france)","res":"paris,france","app":"row(paris,france|tokyo,japan,paris,france)"},
      {"s":"paris,france|tokyo,japan","c":"row(·,tokyo,japan)","res":"tokyo,japan","app":"row(paris,france|tokyo,japan,tokyo,japan)"},
      {"s":"paris:2.35,48.85","c":"cutGroupedFields","res":"paris|2.35,48.85","app":"cutGroupedFields(paris:2.35,48.85)"},
      {"s":"paris:2.35,48.85\ntokyo:139.69,35.68","c":"cutGroupedLines","res":"paris:2.35,48.85|tokyo:139.69,35.68","app":"cutGroupedLines(paris:2.35,48.85\ntokyo:139.69,35.68)"},
      {"s":"paris:2.35,48.85\ntokyo:139.69,35.68","c":"hasFormat(·,grouped)","res":"grouped","app":"hasFormat(paris:2.35,48.85\ntokyo:139.69,35.68,grouped)"},
      {"s":"paris:2.35,48.85|tokyo:139.69,35.68","c":"groupedLine(·,paris:2.35,48.85)","res":"paris:2.35,48.85","app":"groupedLine(paris:2.35,48.85|tokyo:139.69,35.68,paris:2.35,48.85)"},
      {"s":"paris:2.35,48.85|tokyo:139.69,35.68","c":"groupedLine(·,tokyo:139.69,35.68)","res":"tokyo:139.69,35.68","app":"groupedLine(paris:2.35,48.85|tokyo:139.69,35.68,tokyo:139.69,35.68)"},
      {"s":"paris|2.35,48.85","c":"groupedField(·,2.35,48.85)","res":"2.35,48.85","app":"groupedField(paris|2.35,48.85,2.35,48.85)"},
      {"s":"paris|2.35,48.85","c":"groupedField(·,paris)","res":"paris","app":"groupedField(paris|2.35,48.85,paris)"},
      {"s":"paris|france|europe","c":"field(·,europe)","res":"europe","app":"field(paris|france|europe,europe)"},
      {"s":"paris|france|europe","c":"field(·,france)","res":"france","app":"field(paris|france|europe,france)"},
      {"s":"paris|france|europe","c":"field(·,paris)","res":"paris","app":"field(paris|france|europe,paris)"},
      {"s":"paris|sits|on|the|seine","c":"word(·,on)","res":"on","app":"word(paris|sits|on|the|seine,on)"},
      {"s":"paris|sits|on|the|seine","c":"word(·,paris)","res":"paris","app":"word(paris|sits|on|the|seine,paris)"},
      {"s":"paris|sits|on|the|seine","c":"word(·,seine)","res":"seine","app":"word(paris|sits|on|the|seine,seine)"},
      {"s":"paris|sits|on|the|seine","c":"word(·,sits)","res":"sits","app":"word(paris|sits|on|the|seine,sits)"},
      {"s":"paris|sits|on|the|seine","c":"word(·,the)","res":"the","app":"word(paris|sits|on|the|seine,the)"},
      {"s":"tokyo sits on the sumida","c":"cutWords","res":"tokyo|sits|on|the|sumida","app":"cutWords(tokyo sits on the sumida)"},
      {"s":"tokyo,japan","c":"city","res":"tokyo","app":"city(tokyo,japan)"},
      {"s":"tokyo,japan","c":"country","res":"japan","app":"country(tokyo,japan)"},
      {"s":"tokyo,japan,asia","c":"cutFields","res":"tokyo|japan|asia","app":"cutFields(tokyo,japan,asia)"},
      {"s":"tokyo:139.69,35.68","c":"cutGroupedFields","res":"tokyo|139.69,35.68","app":"cutGroupedFields(tokyo:139.69,35.68)"},
      {"s":"tokyo|139.69,35.68","c":"groupedField(·,139.69,35.68)","res":"139.69,35.68","app":"groupedField(tokyo|139.69,35.68,139.69,35.68)"},
      {"s":"tokyo|139.69,35.68","c":"groupedField(·,tokyo)","res":"tokyo","app":"groupedField(tokyo|139.69,35.68,tokyo)"},
      {"s":"tokyo|japan|asia","c":"field(·,asia)","res":"asia","app":"field(tokyo|japan|asia,asia)"},
      {"s":"tokyo|japan|asia","c":"field(·,japan)","res":"japan","app":"field(tokyo|japan|asia,japan)"},
      {"s":"tokyo|japan|asia","c":"field(·,tokyo)","res":"tokyo","app":"field(tokyo|japan|asia,tokyo)"},
      {"s":"tokyo|sits|on|the|sumida","c":"word(·,on)","res":"on","app":"word(tokyo|sits|on|the|sumida,on)"},
      {"s":"tokyo|sits|on|the|sumida","c":"word(·,sits)","res":"sits","app":"word(tokyo|sits|on|the|sumida,sits)"},
      {"s":"tokyo|sits|on|the|sumida","c":"word(·,sumida)","res":"sumida","app":"word(tokyo|sits|on|the|sumida,sumida)"},
      {"s":"tokyo|sits|on|the|sumida","c":"word(·,the)","res":"the","app":"word(tokyo|sits|on|the|sumida,the)"},
      {"s":"tokyo|sits|on|the|sumida","c":"word(·,tokyo)","res":"tokyo","app":"word(tokyo|sits|on|the|sumida,tokyo)"}
    ]
  },
  "tables": [
    {"cols":["place","river"],"rows":["{\"place\":\"paris\",\"river\":\"seine\"}","{\"place\":\"tokyo\",\"river\":\"sumida\"}"]},
    {"cols":["city","country"],"rows":["paris,france","tokyo,japan"]},
    {"cols":["name"],"rows":["name: paris","name: tokyo"]},
    {"cols":["cutPairs"],"rows":["name: paris\nnation: france","name: tokyo\nnation: japan"]},
    {"cols":["nation"],"rows":["nation: france","nation: japan"]},
    {"cols":["cutWords"],"rows":["paris sits on the seine","tokyo sits on the sumida"]},
    {"cols":["cutFields"],"rows":["paris,france,europe","tokyo,japan,asia"]},
    {"cols":["cutGroupedFields"],"rows":["paris:2.35,48.85","tokyo:139.69,35.68"]},
    {"cols":["word(·,on)","word(·,paris)","word(·,seine)","word(·,sits)","word(·,the)"],"rows":["paris|sits|on|the|seine"]},
    {"cols":["word(·,on)","word(·,sits)","word(·,sumida)","word(·,the)","word(·,tokyo)"],"rows":["tokyo|sits|on|the|sumida"]},
    {"cols":["word(·,a)","word(·,city)","word(·,is)","word(·,place)"],"rows":["a|city|is|a|place"]},
    {"cols":["cutSentences","cutWords","sentence"],"rows":["a city is a place"]},
    {"cols":["field(·,europe)","field(·,france)","field(·,paris)"],"rows":["paris|france|europe"]},
    {"cols":["field(·,asia)","field(·,japan)","field(·,tokyo)"],"rows":["tokyo|japan|asia"]},
    {"cols":["cutItems","hasFormat(·,json)"],"rows":["[{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}]"]},
    {"cols":["item(·,{\"place\":\"paris\",\"river\":\"seine\"})","item(·,{\"place\":\"tokyo\",\"river\":\"sumida\"})"],"rows":["{\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"}"]},
    {"cols":["cutRows","hasFormat(·,headered-csv)"],"rows":["city,country\nparis,france\ntokyo,japan"]},
    {"cols":["cutBlocks","hasFormat(·,key-value)"],"rows":["name: paris\nnation: france\n\nname: tokyo\nnation: japan"]},
    {"cols":["block(·,name: paris\nnation: france)","block(·,name: tokyo\nnation: japan)"],"rows":["name: paris\nnation: france|name: tokyo\nnation: japan"]},
    {"cols":["pair(·,name: paris)","pair(·,nation: france)"],"rows":["name: paris|nation: france"]},
    {"cols":["pair(·,name: tokyo)","pair(·,nation: japan)"],"rows":["name: tokyo|nation: japan"]},
    {"cols":["cutParagraphs","hasFormat(·,prose)"],"rows":["paris sits on the seine\ntokyo sits on the sumida\n\na city is a place"]},
    {"cols":["paragraph(·,a city is a place)","paragraph(·,paris sits on the seine\ntokyo sits on the sumida)"],"rows":["paris sits on the seine\ntokyo sits on the sumida|a city is a place"]},
    {"cols":["sentence(·,paris sits on the seine)","sentence(·,tokyo sits on the sumida)"],"rows":["paris sits on the seine|tokyo sits on the sumida"]},
    {"cols":["cutLines","hasFormat(·,bare-csv)"],"rows":["paris,france,europe\ntokyo,japan,asia"]},
    {"cols":["line(·,paris,france,europe)","line(·,tokyo,japan,asia)"],"rows":["paris,france,europe|tokyo,japan,asia"]},
    {"cols":["row(·,paris,france)","row(·,tokyo,japan)"],"rows":["paris,france|tokyo,japan"]},
    {"cols":["cutGroupedLines","hasFormat(·,grouped)"],"rows":["paris:2.35,48.85\ntokyo:139.69,35.68"]},
    {"cols":["groupedLine(·,paris:2.35,48.85)","groupedLine(·,tokyo:139.69,35.68)"],"rows":["paris:2.35,48.85|tokyo:139.69,35.68"]},
    {"cols":["groupedField(·,2.35,48.85)","groupedField(·,paris)"],"rows":["paris|2.35,48.85"]},
    {"cols":["groupedField(·,139.69,35.68)","groupedField(·,tokyo)"],"rows":["tokyo|139.69,35.68"]},
    {"cols":["cutSentences"],"rows":["paris sits on the seine\ntokyo sits on the sumida"]}
  ],
  "chains": [],
  "listings": [
    {"fn":"block","from":"name: paris\nnation: france|name: tokyo\nnation: japan","items":["name: paris\nnation: france","name: tokyo\nnation: japan"]},
    {"fn":"field","from":"paris|france|europe","items":["europe","france","paris"]},
    {"fn":"field","from":"tokyo|japan|asia","items":["asia","japan","tokyo"]},
    {"fn":"groupedField","from":"paris|2.35,48.85","items":["2.35,48.85","paris"]},
    {"fn":"groupedField","from":"tokyo|139.69,35.68","items":["139.69,35.68","tokyo"]},
    {"fn":"groupedLine","from":"paris:2.35,48.85|tokyo:139.69,35.68","items":["paris:2.35,48.85","tokyo:139.69,35.68"]},
    {"fn":"hasFormat","from":"[{\"place\":\"paris\",\"river\":\"seine\"},{\"place\":\"tokyo\",\"river\":\"sumida\"}]","items":["json"]},
    {"fn":"hasFormat","from":"city,country\nparis,france\ntokyo,japan","items":["headered-csv"]},
    {"fn":"hasFormat","from":"name: paris\nnation: france\n\nname: tokyo\nnation: japan","items":["key-value"]},
    {"fn":"hasFormat","from":"paris sits on the seine\ntokyo sits on the sumida\n\na city is a place","items":["prose"]},
    {"fn":"hasFormat","from":"paris,france,europe\ntokyo,japan,asia","items":["bare-csv"]},
    {"fn":"hasFormat","from":"paris:2.35,48.85\ntokyo:139.69,35.68","items":["grouped"]},
    {"fn":"item","from":"{\"place\":\"paris\",\"river\":\"seine\"}|{\"place\":\"tokyo\",\"river\":\"sumida\"}","items":["{\"place\":\"paris\",\"river\":\"seine\"}","{\"place\":\"tokyo\",\"river\":\"sumida\"}"]},
    {"fn":"line","from":"paris,france,europe|tokyo,japan,asia","items":["paris,france,europe","tokyo,japan,asia"]},
    {"fn":"pair","from":"name: paris|nation: france","items":["name: paris","nation: france"]},
    {"fn":"pair","from":"name: tokyo|nation: japan","items":["name: tokyo","nation: japan"]},
    {"fn":"paragraph","from":"paris sits on the seine\ntokyo sits on the sumida|a city is a place","items":["a city is a place","paris sits on the seine\ntokyo sits on the sumida"]},
    {"fn":"row","from":"paris,france|tokyo,japan","items":["paris,france","tokyo,japan"]},
    {"fn":"sentence","from":"paris sits on the seine|tokyo sits on the sumida","items":["paris sits on the seine","tokyo sits on the sumida"]},
    {"fn":"word","from":"a|city|is|a|place","items":["a","city","is","place"]},
    {"fn":"word","from":"paris|sits|on|the|seine","items":["on","paris","seine","sits","the"]},
    {"fn":"word","from":"tokyo|sits|on|the|sumida","items":["on","sits","sumida","the","tokyo"]}
  ]
};
