window.GRAPH = {
  "nodes": [
    {"id":"10.0.0.5","label":"10.0.0.5","role":"value"},
    {"id":"10.0.0.5:22","label":"10.0.0.5:22","role":"value"},
    {"id":"192.168.1.10","label":"192.168.1.10","role":"value"},
    {"id":"192.168.1.10:443","label":"192.168.1.10:443","role":"value"},
    {"id":"192.168.1.10:8080","label":"192.168.1.10:8080","role":"value"},
    {"id":"22","label":"22","role":"value"},
    {"id":"443","label":"443","role":"value"},
    {"id":"8080","label":"8080","role":"value"},
    {"id":"alice","label":"alice","role":"value"},
    {"id":"alice brown","label":"alice brown","role":"value"},
    {"id":"brown","label":"brown","role":"value"},
    {"id":"brown, alice","label":"brown, alice","role":"value"},
    {"id":"carol","label":"carol","role":"value"},
    {"id":"carol,white","label":"carol,white","role":"value"},
    {"id":"carol,white|dave,green","label":"carol,white|dave,green","role":"value"},
    {"id":"cutRows()","label":"cutRows()","role":"function"},
    {"id":"cutRows(first,last\ncarol,white\ndave,green)","label":"cutRows(first,last\ncarol,white\ndave,green)","role":"application"},
    {"id":"dave","label":"dave","role":"value"},
    {"id":"dave,green","label":"dave,green","role":"value"},
    {"id":"first()","label":"first()","role":"function"},
    {"id":"first(carol,white)","label":"first(carol,white)","role":"application"},
    {"id":"first(dave,green)","label":"first(dave,green)","role":"application"},
    {"id":"first,last","label":"first,last","role":"value"},
    {"id":"first,last\ncarol,white\ndave,green","label":"first,last\ncarol,white\ndave,green","role":"value"},
    {"id":"firstName()","label":"firstName()","role":"function"},
    {"id":"firstName(alice brown)","label":"firstName(alice brown)","role":"application"},
    {"id":"firstName(brown, alice)","label":"firstName(brown, alice)","role":"application"},
    {"id":"firstName(robert smith)","label":"firstName(robert smith)","role":"application"},
    {"id":"firstName(smith, robert)","label":"firstName(smith, robert)","role":"application"},
    {"id":"green","label":"green","role":"value"},
    {"id":"headerLine()","label":"headerLine()","role":"function"},
    {"id":"headerLine(first,last\ncarol,white\ndave,green)","label":"headerLine(first,last\ncarol,white\ndave,green)","role":"application"},
    {"id":"ip()","label":"ip()","role":"function"},
    {"id":"ip(10.0.0.5:22)","label":"ip(10.0.0.5:22)","role":"application"},
    {"id":"ip(192.168.1.10:443)","label":"ip(192.168.1.10:443)","role":"application"},
    {"id":"ip(192.168.1.10:8080)","label":"ip(192.168.1.10:8080)","role":"application"},
    {"id":"last()","label":"last()","role":"function"},
    {"id":"last(carol,white)","label":"last(carol,white)","role":"application"},
    {"id":"last(dave,green)","label":"last(dave,green)","role":"application"},
    {"id":"lastName()","label":"lastName()","role":"function"},
    {"id":"lastName(alice brown)","label":"lastName(alice brown)","role":"application"},
    {"id":"lastName(brown, alice)","label":"lastName(brown, alice)","role":"application"},
    {"id":"lastName(robert smith)","label":"lastName(robert smith)","role":"application"},
    {"id":"lastName(smith, robert)","label":"lastName(smith, robert)","role":"application"},
    {"id":"port()","label":"port()","role":"function"},
    {"id":"port(10.0.0.5:22)","label":"port(10.0.0.5:22)","role":"application"},
    {"id":"port(192.168.1.10:443)","label":"port(192.168.1.10:443)","role":"application"},
    {"id":"port(192.168.1.10:8080)","label":"port(192.168.1.10:8080)","role":"application"},
    {"id":"robert","label":"robert","role":"value"},
    {"id":"robert smith","label":"robert smith","role":"value"},
    {"id":"row()","label":"row()","role":"function"},
    {"id":"row(carol,white|dave,green,carol,white)","label":"row(carol,white|dave,green,carol,white)","role":"application"},
    {"id":"row(carol,white|dave,green,dave,green)","label":"row(carol,white|dave,green,dave,green)","role":"application"},
    {"id":"smith","label":"smith","role":"value"},
    {"id":"smith, robert","label":"smith, robert","role":"value"},
    {"id":"white","label":"white","role":"value"}
  ],
  "edges": [
    {"from":"10.0.0.5:22","to":"ip(10.0.0.5:22)"},
    {"from":"10.0.0.5:22","to":"port(10.0.0.5:22)"},
    {"from":"192.168.1.10:443","to":"ip(192.168.1.10:443)"},
    {"from":"192.168.1.10:443","to":"port(192.168.1.10:443)"},
    {"from":"192.168.1.10:8080","to":"ip(192.168.1.10:8080)"},
    {"from":"192.168.1.10:8080","to":"port(192.168.1.10:8080)"},
    {"from":"alice brown","to":"firstName(alice brown)"},
    {"from":"alice brown","to":"lastName(alice brown)"},
    {"from":"brown, alice","to":"firstName(brown, alice)"},
    {"from":"brown, alice","to":"lastName(brown, alice)"},
    {"from":"carol,white","to":"first(carol,white)"},
    {"from":"carol,white","to":"last(carol,white)"},
    {"from":"carol,white","to":"row(carol,white|dave,green,carol,white)"},
    {"from":"carol,white|dave,green","to":"row(carol,white|dave,green,carol,white)"},
    {"from":"carol,white|dave,green","to":"row(carol,white|dave,green,dave,green)"},
    {"from":"cutRows()","to":"cutRows(first,last\ncarol,white\ndave,green)"},
    {"from":"cutRows(first,last\ncarol,white\ndave,green)","to":"carol,white|dave,green"},
    {"from":"dave,green","to":"first(dave,green)"},
    {"from":"dave,green","to":"last(dave,green)"},
    {"from":"dave,green","to":"row(carol,white|dave,green,dave,green)"},
    {"from":"first()","to":"first(carol,white)"},
    {"from":"first()","to":"first(dave,green)"},
    {"from":"first(carol,white)","to":"carol"},
    {"from":"first(dave,green)","to":"dave"},
    {"from":"first,last\ncarol,white\ndave,green","to":"cutRows(first,last\ncarol,white\ndave,green)"},
    {"from":"first,last\ncarol,white\ndave,green","to":"headerLine(first,last\ncarol,white\ndave,green)"},
    {"from":"firstName()","to":"firstName(alice brown)"},
    {"from":"firstName()","to":"firstName(brown, alice)"},
    {"from":"firstName()","to":"firstName(robert smith)"},
    {"from":"firstName()","to":"firstName(smith, robert)"},
    {"from":"firstName(alice brown)","to":"alice"},
    {"from":"firstName(brown, alice)","to":"alice"},
    {"from":"firstName(robert smith)","to":"robert"},
    {"from":"firstName(smith, robert)","to":"robert"},
    {"from":"headerLine()","to":"headerLine(first,last\ncarol,white\ndave,green)"},
    {"from":"headerLine(first,last\ncarol,white\ndave,green)","to":"first,last"},
    {"from":"ip()","to":"ip(10.0.0.5:22)"},
    {"from":"ip()","to":"ip(192.168.1.10:443)"},
    {"from":"ip()","to":"ip(192.168.1.10:8080)"},
    {"from":"ip(10.0.0.5:22)","to":"10.0.0.5"},
    {"from":"ip(192.168.1.10:443)","to":"192.168.1.10"},
    {"from":"ip(192.168.1.10:8080)","to":"192.168.1.10"},
    {"from":"last()","to":"last(carol,white)"},
    {"from":"last()","to":"last(dave,green)"},
    {"from":"last(carol,white)","to":"white"},
    {"from":"last(dave,green)","to":"green"},
    {"from":"lastName()","to":"lastName(alice brown)"},
    {"from":"lastName()","to":"lastName(brown, alice)"},
    {"from":"lastName()","to":"lastName(robert smith)"},
    {"from":"lastName()","to":"lastName(smith, robert)"},
    {"from":"lastName(alice brown)","to":"brown"},
    {"from":"lastName(brown, alice)","to":"brown"},
    {"from":"lastName(robert smith)","to":"smith"},
    {"from":"lastName(smith, robert)","to":"smith"},
    {"from":"port()","to":"port(10.0.0.5:22)"},
    {"from":"port()","to":"port(192.168.1.10:443)"},
    {"from":"port()","to":"port(192.168.1.10:8080)"},
    {"from":"port(10.0.0.5:22)","to":"22"},
    {"from":"port(192.168.1.10:443)","to":"443"},
    {"from":"port(192.168.1.10:8080)","to":"8080"},
    {"from":"robert smith","to":"firstName(robert smith)"},
    {"from":"robert smith","to":"lastName(robert smith)"},
    {"from":"row()","to":"row(carol,white|dave,green,carol,white)"},
    {"from":"row()","to":"row(carol,white|dave,green,dave,green)"},
    {"from":"row(carol,white|dave,green,carol,white)","to":"carol,white"},
    {"from":"row(carol,white|dave,green,dave,green)","to":"dave,green"},
    {"from":"smith, robert","to":"firstName(smith, robert)"},
    {"from":"smith, robert","to":"lastName(smith, robert)"}
  ],
  "pivot": {
    "subjects": [
      "10.0.0.5:22",
      "192.168.1.10:443",
      "192.168.1.10:8080",
      "alice brown",
      "brown, alice",
      "carol,white",
      "carol,white|dave,green",
      "dave,green",
      "first,last\ncarol,white\ndave,green",
      "robert smith",
      "smith, robert"
    ],
    "columns": [
      "cutRows",
      "first",
      "firstName",
      "headerLine",
      "ip",
      "last",
      "lastName",
      "port",
      "row(·,carol,white)",
      "row(·,dave,green)"
    ],
    "cells": [
      {"s":"10.0.0.5:22","c":"ip","res":"10.0.0.5","app":"ip(10.0.0.5:22)"},
      {"s":"10.0.0.5:22","c":"port","res":"22","app":"port(10.0.0.5:22)"},
      {"s":"192.168.1.10:443","c":"ip","res":"192.168.1.10","app":"ip(192.168.1.10:443)"},
      {"s":"192.168.1.10:443","c":"port","res":"443","app":"port(192.168.1.10:443)"},
      {"s":"192.168.1.10:8080","c":"ip","res":"192.168.1.10","app":"ip(192.168.1.10:8080)"},
      {"s":"192.168.1.10:8080","c":"port","res":"8080","app":"port(192.168.1.10:8080)"},
      {"s":"alice brown","c":"firstName","res":"alice","app":"firstName(alice brown)"},
      {"s":"alice brown","c":"lastName","res":"brown","app":"lastName(alice brown)"},
      {"s":"brown, alice","c":"firstName","res":"alice","app":"firstName(brown, alice)"},
      {"s":"brown, alice","c":"lastName","res":"brown","app":"lastName(brown, alice)"},
      {"s":"carol,white","c":"first","res":"carol","app":"first(carol,white)"},
      {"s":"carol,white","c":"last","res":"white","app":"last(carol,white)"},
      {"s":"carol,white|dave,green","c":"row(·,carol,white)","res":"carol,white","app":"row(carol,white|dave,green,carol,white)"},
      {"s":"carol,white|dave,green","c":"row(·,dave,green)","res":"dave,green","app":"row(carol,white|dave,green,dave,green)"},
      {"s":"dave,green","c":"first","res":"dave","app":"first(dave,green)"},
      {"s":"dave,green","c":"last","res":"green","app":"last(dave,green)"},
      {"s":"first,last\ncarol,white\ndave,green","c":"cutRows","res":"carol,white|dave,green","app":"cutRows(first,last\ncarol,white\ndave,green)"},
      {"s":"first,last\ncarol,white\ndave,green","c":"headerLine","res":"first,last","app":"headerLine(first,last\ncarol,white\ndave,green)"},
      {"s":"robert smith","c":"firstName","res":"robert","app":"firstName(robert smith)"},
      {"s":"robert smith","c":"lastName","res":"smith","app":"lastName(robert smith)"},
      {"s":"smith, robert","c":"firstName","res":"robert","app":"firstName(smith, robert)"},
      {"s":"smith, robert","c":"lastName","res":"smith","app":"lastName(smith, robert)"}
    ]
  },
  "tables": [
    {"cols":["firstName","lastName"],"rows":["alice brown","brown, alice","robert smith","smith, robert"]},
    {"cols":["ip","port"],"rows":["10.0.0.5:22","192.168.1.10:443","192.168.1.10:8080"]},
    {"cols":["first","last"],"rows":["carol,white","dave,green"]},
    {"cols":["row(·,carol,white)","row(·,dave,green)"],"rows":["carol,white|dave,green"]},
    {"cols":["cutRows","headerLine"],"rows":["first,last\ncarol,white\ndave,green"]}
  ],
  "chains": [],
  "listings": [
    {"fn":"row","from":"carol,white|dave,green","items":["carol,white","dave,green"]}
  ]
};
