window.GRAPH = {
  "nodes": [
    {"id":"0","label":"0","role":"value"},
    {"id":"1","label":"1","role":"value"},
    {"id":"2","label":"2","role":"value"},
    {"id":"3","label":"3","role":"value"},
    {"id":"4","label":"4","role":"value"},
    {"id":"a","label":"a","role":"value"},
    {"id":"a city is a place","label":"a city is a place","role":"value"},
    {"id":"city","label":"city","role":"value"},
    {"id":"is","label":"is","role":"value"},
    {"id":"new","label":"new","role":"value"},
    {"id":"old","label":"old","role":"value"},
    {"id":"paragraph()","label":"paragraph()","role":"function"},
    {"id":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,0)","label":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,0)","role":"application"},
    {"id":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,1)","label":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,1)","role":"application"},
    {"id":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,2)","label":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,2)","role":"application"},
    {"id":"paris","label":"paris","role":"value"},
    {"id":"paris is a city","label":"paris is a city","role":"value"},
    {"id":"paris is a city\nthe city is old","label":"paris is a city\nthe city is old","role":"value"},
    {"id":"paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place","label":"paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place","role":"value"},
    {"id":"place","label":"place","role":"value"},
    {"id":"sentence()","label":"sentence()","role":"function"},
    {"id":"sentence(a city is a place,0)","label":"sentence(a city is a place,0)","role":"application"},
    {"id":"sentence(paris is a city\nthe city is old,0)","label":"sentence(paris is a city\nthe city is old,0)","role":"application"},
    {"id":"sentence(paris is a city\nthe city is old,1)","label":"sentence(paris is a city\nthe city is old,1)","role":"application"},
    {"id":"sentence(tokyo is a city\nthe city is new,0)","label":"sentence(tokyo is a city\nthe city is new,0)","role":"application"},
    {"id":"sentence(tokyo is a city\nthe city is new,1)","label":"sentence(tokyo is a city\nthe city is new,1)","role":"application"},
    {"id":"the","label":"the","role":"value"},
    {"id":"the city is new","label":"the city is new","role":"value"},
    {"id":"the city is old","label":"the city is old","role":"value"},
    {"id":"tokyo","label":"tokyo","role":"value"},
    {"id":"tokyo is a city","label":"tokyo is a city","role":"value"},
    {"id":"tokyo is a city\nthe city is new","label":"tokyo is a city\nthe city is new","role":"value"},
    {"id":"word()","label":"word()","role":"function"},
    {"id":"word(a city is a place,0)","label":"word(a city is a place,0)","role":"application"},
    {"id":"word(a city is a place,1)","label":"word(a city is a place,1)","role":"application"},
    {"id":"word(a city is a place,2)","label":"word(a city is a place,2)","role":"application"},
    {"id":"word(a city is a place,3)","label":"word(a city is a place,3)","role":"application"},
    {"id":"word(a city is a place,4)","label":"word(a city is a place,4)","role":"application"},
    {"id":"word(paris is a city,0)","label":"word(paris is a city,0)","role":"application"},
    {"id":"word(paris is a city,1)","label":"word(paris is a city,1)","role":"application"},
    {"id":"word(paris is a city,2)","label":"word(paris is a city,2)","role":"application"},
    {"id":"word(paris is a city,3)","label":"word(paris is a city,3)","role":"application"},
    {"id":"word(the city is new,0)","label":"word(the city is new,0)","role":"application"},
    {"id":"word(the city is new,1)","label":"word(the city is new,1)","role":"application"},
    {"id":"word(the city is new,2)","label":"word(the city is new,2)","role":"application"},
    {"id":"word(the city is new,3)","label":"word(the city is new,3)","role":"application"},
    {"id":"word(the city is old,0)","label":"word(the city is old,0)","role":"application"},
    {"id":"word(the city is old,1)","label":"word(the city is old,1)","role":"application"},
    {"id":"word(the city is old,2)","label":"word(the city is old,2)","role":"application"},
    {"id":"word(the city is old,3)","label":"word(the city is old,3)","role":"application"},
    {"id":"word(tokyo is a city,0)","label":"word(tokyo is a city,0)","role":"application"},
    {"id":"word(tokyo is a city,1)","label":"word(tokyo is a city,1)","role":"application"},
    {"id":"word(tokyo is a city,2)","label":"word(tokyo is a city,2)","role":"application"},
    {"id":"word(tokyo is a city,3)","label":"word(tokyo is a city,3)","role":"application"},
    {"id":"∅","label":"∅","role":"value"}
  ],
  "edges": [
    {"from":"0","to":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,0)"},
    {"from":"0","to":"sentence(a city is a place,0)"},
    {"from":"0","to":"sentence(paris is a city\nthe city is old,0)"},
    {"from":"0","to":"sentence(tokyo is a city\nthe city is new,0)"},
    {"from":"0","to":"word(a city is a place,0)"},
    {"from":"0","to":"word(paris is a city,0)"},
    {"from":"0","to":"word(the city is new,0)"},
    {"from":"0","to":"word(the city is old,0)"},
    {"from":"0","to":"word(tokyo is a city,0)"},
    {"from":"1","to":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,1)"},
    {"from":"1","to":"sentence(paris is a city\nthe city is old,1)"},
    {"from":"1","to":"sentence(tokyo is a city\nthe city is new,1)"},
    {"from":"1","to":"word(a city is a place,1)"},
    {"from":"1","to":"word(paris is a city,1)"},
    {"from":"1","to":"word(the city is new,1)"},
    {"from":"1","to":"word(the city is old,1)"},
    {"from":"1","to":"word(tokyo is a city,1)"},
    {"from":"2","to":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,2)"},
    {"from":"2","to":"word(a city is a place,2)"},
    {"from":"2","to":"word(paris is a city,2)"},
    {"from":"2","to":"word(the city is new,2)"},
    {"from":"2","to":"word(the city is old,2)"},
    {"from":"2","to":"word(tokyo is a city,2)"},
    {"from":"3","to":"word(a city is a place,3)"},
    {"from":"3","to":"word(paris is a city,3)"},
    {"from":"3","to":"word(the city is new,3)"},
    {"from":"3","to":"word(the city is old,3)"},
    {"from":"3","to":"word(tokyo is a city,3)"},
    {"from":"4","to":"word(a city is a place,4)"},
    {"from":"a city is a place","to":"sentence(a city is a place,0)"},
    {"from":"a city is a place","to":"word(a city is a place,0)"},
    {"from":"a city is a place","to":"word(a city is a place,1)"},
    {"from":"a city is a place","to":"word(a city is a place,2)"},
    {"from":"a city is a place","to":"word(a city is a place,3)"},
    {"from":"a city is a place","to":"word(a city is a place,4)"},
    {"from":"paragraph()","to":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,0)"},
    {"from":"paragraph()","to":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,1)"},
    {"from":"paragraph()","to":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,2)"},
    {"from":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,0)","to":"paris is a city\nthe city is old"},
    {"from":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,1)","to":"tokyo is a city\nthe city is new"},
    {"from":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,2)","to":"a city is a place"},
    {"from":"paris is a city","to":"word(paris is a city,0)"},
    {"from":"paris is a city","to":"word(paris is a city,1)"},
    {"from":"paris is a city","to":"word(paris is a city,2)"},
    {"from":"paris is a city","to":"word(paris is a city,3)"},
    {"from":"paris is a city\nthe city is old","to":"sentence(paris is a city\nthe city is old,0)"},
    {"from":"paris is a city\nthe city is old","to":"sentence(paris is a city\nthe city is old,1)"},
    {"from":"paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place","to":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,0)"},
    {"from":"paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place","to":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,1)"},
    {"from":"paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place","to":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,2)"},
    {"from":"sentence()","to":"sentence(a city is a place,0)"},
    {"from":"sentence()","to":"sentence(paris is a city\nthe city is old,0)"},
    {"from":"sentence()","to":"sentence(paris is a city\nthe city is old,1)"},
    {"from":"sentence()","to":"sentence(tokyo is a city\nthe city is new,0)"},
    {"from":"sentence()","to":"sentence(tokyo is a city\nthe city is new,1)"},
    {"from":"sentence(a city is a place,0)","to":"a city is a place"},
    {"from":"sentence(paris is a city\nthe city is old,0)","to":"paris is a city"},
    {"from":"sentence(paris is a city\nthe city is old,1)","to":"the city is old"},
    {"from":"sentence(tokyo is a city\nthe city is new,0)","to":"tokyo is a city"},
    {"from":"sentence(tokyo is a city\nthe city is new,1)","to":"the city is new"},
    {"from":"the city is new","to":"word(the city is new,0)"},
    {"from":"the city is new","to":"word(the city is new,1)"},
    {"from":"the city is new","to":"word(the city is new,2)"},
    {"from":"the city is new","to":"word(the city is new,3)"},
    {"from":"the city is old","to":"word(the city is old,0)"},
    {"from":"the city is old","to":"word(the city is old,1)"},
    {"from":"the city is old","to":"word(the city is old,2)"},
    {"from":"the city is old","to":"word(the city is old,3)"},
    {"from":"tokyo is a city","to":"word(tokyo is a city,0)"},
    {"from":"tokyo is a city","to":"word(tokyo is a city,1)"},
    {"from":"tokyo is a city","to":"word(tokyo is a city,2)"},
    {"from":"tokyo is a city","to":"word(tokyo is a city,3)"},
    {"from":"tokyo is a city\nthe city is new","to":"sentence(tokyo is a city\nthe city is new,0)"},
    {"from":"tokyo is a city\nthe city is new","to":"sentence(tokyo is a city\nthe city is new,1)"},
    {"from":"word()","to":"word(a city is a place,0)"},
    {"from":"word()","to":"word(a city is a place,1)"},
    {"from":"word()","to":"word(a city is a place,2)"},
    {"from":"word()","to":"word(a city is a place,3)"},
    {"from":"word()","to":"word(a city is a place,4)"},
    {"from":"word()","to":"word(paris is a city,0)"},
    {"from":"word()","to":"word(paris is a city,1)"},
    {"from":"word()","to":"word(paris is a city,2)"},
    {"from":"word()","to":"word(paris is a city,3)"},
    {"from":"word()","to":"word(the city is new,0)"},
    {"from":"word()","to":"word(the city is new,1)"},
    {"from":"word()","to":"word(the city is new,2)"},
    {"from":"word()","to":"word(the city is new,3)"},
    {"from":"word()","to":"word(the city is old,0)"},
    {"from":"word()","to":"word(the city is old,1)"},
    {"from":"word()","to":"word(the city is old,2)"},
    {"from":"word()","to":"word(the city is old,3)"},
    {"from":"word()","to":"word(tokyo is a city,0)"},
    {"from":"word()","to":"word(tokyo is a city,1)"},
    {"from":"word()","to":"word(tokyo is a city,2)"},
    {"from":"word()","to":"word(tokyo is a city,3)"},
    {"from":"word(a city is a place,0)","to":"a"},
    {"from":"word(a city is a place,1)","to":"city"},
    {"from":"word(a city is a place,2)","to":"is"},
    {"from":"word(a city is a place,3)","to":"a"},
    {"from":"word(a city is a place,4)","to":"place"},
    {"from":"word(paris is a city,0)","to":"paris"},
    {"from":"word(paris is a city,1)","to":"is"},
    {"from":"word(paris is a city,2)","to":"a"},
    {"from":"word(paris is a city,3)","to":"city"},
    {"from":"word(the city is new,0)","to":"the"},
    {"from":"word(the city is new,1)","to":"city"},
    {"from":"word(the city is new,2)","to":"is"},
    {"from":"word(the city is new,3)","to":"new"},
    {"from":"word(the city is old,0)","to":"the"},
    {"from":"word(the city is old,1)","to":"city"},
    {"from":"word(the city is old,2)","to":"is"},
    {"from":"word(the city is old,3)","to":"old"},
    {"from":"word(tokyo is a city,0)","to":"tokyo"},
    {"from":"word(tokyo is a city,1)","to":"is"},
    {"from":"word(tokyo is a city,2)","to":"a"},
    {"from":"word(tokyo is a city,3)","to":"city"}
  ],
  "pivot": {
    "subjects": [
      "a city is a place",
      "paris is a city",
      "paris is a city\nthe city is old",
      "paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place",
      "the city is new",
      "the city is old",
      "tokyo is a city",
      "tokyo is a city\nthe city is new"
    ],
    "columns": [
      "paragraph(·,0)",
      "paragraph(·,1)",
      "paragraph(·,2)",
      "sentence(·,0)",
      "sentence(·,1)",
      "word(·,0)",
      "word(·,1)",
      "word(·,2)",
      "word(·,3)",
      "word(·,4)"
    ],
    "cells": [
      {"s":"a city is a place","c":"sentence(·,0)","res":"a city is a place","app":"sentence(a city is a place,0)"},
      {"s":"a city is a place","c":"word(·,0)","res":"a","app":"word(a city is a place,0)"},
      {"s":"a city is a place","c":"word(·,1)","res":"city","app":"word(a city is a place,1)"},
      {"s":"a city is a place","c":"word(·,2)","res":"is","app":"word(a city is a place,2)"},
      {"s":"a city is a place","c":"word(·,3)","res":"a","app":"word(a city is a place,3)"},
      {"s":"a city is a place","c":"word(·,4)","res":"place","app":"word(a city is a place,4)"},
      {"s":"paris is a city","c":"word(·,0)","res":"paris","app":"word(paris is a city,0)"},
      {"s":"paris is a city","c":"word(·,1)","res":"is","app":"word(paris is a city,1)"},
      {"s":"paris is a city","c":"word(·,2)","res":"a","app":"word(paris is a city,2)"},
      {"s":"paris is a city","c":"word(·,3)","res":"city","app":"word(paris is a city,3)"},
      {"s":"paris is a city\nthe city is old","c":"sentence(·,0)","res":"paris is a city","app":"sentence(paris is a city\nthe city is old,0)"},
      {"s":"paris is a city\nthe city is old","c":"sentence(·,1)","res":"the city is old","app":"sentence(paris is a city\nthe city is old,1)"},
      {"s":"paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place","c":"paragraph(·,0)","res":"paris is a city\nthe city is old","app":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,0)"},
      {"s":"paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place","c":"paragraph(·,1)","res":"tokyo is a city\nthe city is new","app":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,1)"},
      {"s":"paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place","c":"paragraph(·,2)","res":"a city is a place","app":"paragraph(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place,2)"},
      {"s":"the city is new","c":"word(·,0)","res":"the","app":"word(the city is new,0)"},
      {"s":"the city is new","c":"word(·,1)","res":"city","app":"word(the city is new,1)"},
      {"s":"the city is new","c":"word(·,2)","res":"is","app":"word(the city is new,2)"},
      {"s":"the city is new","c":"word(·,3)","res":"new","app":"word(the city is new,3)"},
      {"s":"the city is old","c":"word(·,0)","res":"the","app":"word(the city is old,0)"},
      {"s":"the city is old","c":"word(·,1)","res":"city","app":"word(the city is old,1)"},
      {"s":"the city is old","c":"word(·,2)","res":"is","app":"word(the city is old,2)"},
      {"s":"the city is old","c":"word(·,3)","res":"old","app":"word(the city is old,3)"},
      {"s":"tokyo is a city","c":"word(·,0)","res":"tokyo","app":"word(tokyo is a city,0)"},
      {"s":"tokyo is a city","c":"word(·,1)","res":"is","app":"word(tokyo is a city,1)"},
      {"s":"tokyo is a city","c":"word(·,2)","res":"a","app":"word(tokyo is a city,2)"},
      {"s":"tokyo is a city","c":"word(·,3)","res":"city","app":"word(tokyo is a city,3)"},
      {"s":"tokyo is a city\nthe city is new","c":"sentence(·,0)","res":"tokyo is a city","app":"sentence(tokyo is a city\nthe city is new,0)"},
      {"s":"tokyo is a city\nthe city is new","c":"sentence(·,1)","res":"the city is new","app":"sentence(tokyo is a city\nthe city is new,1)"}
    ]
  },
  "tables": [
    {"cols":["word(·,0)","word(·,1)","word(·,2)","word(·,3)"],"rows":["paris is a city","the city is new","the city is old","tokyo is a city"]},
    {"cols":["sentence(·,0)","sentence(·,1)"],"rows":["paris is a city\nthe city is old","tokyo is a city\nthe city is new"]},
    {"cols":["sentence(·,0)","word(·,0)","word(·,1)","word(·,2)","word(·,3)","word(·,4)"],"rows":["a city is a place"]},
    {"cols":["paragraph(·,0)","paragraph(·,1)","paragraph(·,2)"],"rows":["paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place"]}
  ],
  "chains": [],
  "listings": []
};
