window.GRAPH = {
  "nodes": [
    {"id":"a","label":"a","role":"value"},
    {"id":"a city is a place","label":"a city is a place","role":"value"},
    {"id":"a|city|is|a|place","label":"a|city|is|a|place","role":"value"},
    {"id":"city","label":"city","role":"value"},
    {"id":"cutParagraphs()","label":"cutParagraphs()","role":"function"},
    {"id":"cutParagraphs(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place)","label":"cutParagraphs(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place)","role":"application"},
    {"id":"cutSentences()","label":"cutSentences()","role":"function"},
    {"id":"cutSentences(a city is a place)","label":"cutSentences(a city is a place)","role":"application"},
    {"id":"cutSentences(paris is a city\nthe city is old)","label":"cutSentences(paris is a city\nthe city is old)","role":"application"},
    {"id":"cutSentences(tokyo is a city\nthe city is new)","label":"cutSentences(tokyo is a city\nthe city is new)","role":"application"},
    {"id":"cutWords()","label":"cutWords()","role":"function"},
    {"id":"cutWords(a city is a place)","label":"cutWords(a city is a place)","role":"application"},
    {"id":"cutWords(paris is a city)","label":"cutWords(paris is a city)","role":"application"},
    {"id":"cutWords(the city is new)","label":"cutWords(the city is new)","role":"application"},
    {"id":"cutWords(the city is old)","label":"cutWords(the city is old)","role":"application"},
    {"id":"cutWords(tokyo is a city)","label":"cutWords(tokyo is a city)","role":"application"},
    {"id":"is","label":"is","role":"value"},
    {"id":"new","label":"new","role":"value"},
    {"id":"old","label":"old","role":"value"},
    {"id":"paragraph()","label":"paragraph()","role":"function"},
    {"id":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,a city is a place)","label":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,a city is a place)","role":"application"},
    {"id":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,paris is a city\nthe city is old)","label":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,paris is a city\nthe city is old)","role":"application"},
    {"id":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,tokyo is a city\nthe city is new)","label":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,tokyo is a city\nthe city is new)","role":"application"},
    {"id":"paris","label":"paris","role":"value"},
    {"id":"paris is a city","label":"paris is a city","role":"value"},
    {"id":"paris is a city\nthe city is old","label":"paris is a city\nthe city is old","role":"value"},
    {"id":"paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place","label":"paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place","role":"value"},
    {"id":"paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place","label":"paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place","role":"value"},
    {"id":"paris is a city|the city is old","label":"paris is a city|the city is old","role":"value"},
    {"id":"paris|is|a|city","label":"paris|is|a|city","role":"value"},
    {"id":"place","label":"place","role":"value"},
    {"id":"sentence()","label":"sentence()","role":"function"},
    {"id":"sentence(a city is a place,a city is a place)","label":"sentence(a city is a place,a city is a place)","role":"application"},
    {"id":"sentence(paris is a city|the city is old,paris is a city)","label":"sentence(paris is a city|the city is old,paris is a city)","role":"application"},
    {"id":"sentence(paris is a city|the city is old,the city is old)","label":"sentence(paris is a city|the city is old,the city is old)","role":"application"},
    {"id":"sentence(tokyo is a city|the city is new,the city is new)","label":"sentence(tokyo is a city|the city is new,the city is new)","role":"application"},
    {"id":"sentence(tokyo is a city|the city is new,tokyo is a city)","label":"sentence(tokyo is a city|the city is new,tokyo is a city)","role":"application"},
    {"id":"the","label":"the","role":"value"},
    {"id":"the city is new","label":"the city is new","role":"value"},
    {"id":"the city is old","label":"the city is old","role":"value"},
    {"id":"the|city|is|new","label":"the|city|is|new","role":"value"},
    {"id":"the|city|is|old","label":"the|city|is|old","role":"value"},
    {"id":"tokyo","label":"tokyo","role":"value"},
    {"id":"tokyo is a city","label":"tokyo is a city","role":"value"},
    {"id":"tokyo is a city\nthe city is new","label":"tokyo is a city\nthe city is new","role":"value"},
    {"id":"tokyo is a city|the city is new","label":"tokyo is a city|the city is new","role":"value"},
    {"id":"tokyo|is|a|city","label":"tokyo|is|a|city","role":"value"},
    {"id":"word()","label":"word()","role":"function"},
    {"id":"word(a|city|is|a|place,a)","label":"word(a|city|is|a|place,a)","role":"application"},
    {"id":"word(a|city|is|a|place,city)","label":"word(a|city|is|a|place,city)","role":"application"},
    {"id":"word(a|city|is|a|place,is)","label":"word(a|city|is|a|place,is)","role":"application"},
    {"id":"word(a|city|is|a|place,place)","label":"word(a|city|is|a|place,place)","role":"application"},
    {"id":"word(paris|is|a|city,a)","label":"word(paris|is|a|city,a)","role":"application"},
    {"id":"word(paris|is|a|city,city)","label":"word(paris|is|a|city,city)","role":"application"},
    {"id":"word(paris|is|a|city,is)","label":"word(paris|is|a|city,is)","role":"application"},
    {"id":"word(paris|is|a|city,paris)","label":"word(paris|is|a|city,paris)","role":"application"},
    {"id":"word(the|city|is|new,city)","label":"word(the|city|is|new,city)","role":"application"},
    {"id":"word(the|city|is|new,is)","label":"word(the|city|is|new,is)","role":"application"},
    {"id":"word(the|city|is|new,new)","label":"word(the|city|is|new,new)","role":"application"},
    {"id":"word(the|city|is|new,the)","label":"word(the|city|is|new,the)","role":"application"},
    {"id":"word(the|city|is|old,city)","label":"word(the|city|is|old,city)","role":"application"},
    {"id":"word(the|city|is|old,is)","label":"word(the|city|is|old,is)","role":"application"},
    {"id":"word(the|city|is|old,old)","label":"word(the|city|is|old,old)","role":"application"},
    {"id":"word(the|city|is|old,the)","label":"word(the|city|is|old,the)","role":"application"},
    {"id":"word(tokyo|is|a|city,a)","label":"word(tokyo|is|a|city,a)","role":"application"},
    {"id":"word(tokyo|is|a|city,city)","label":"word(tokyo|is|a|city,city)","role":"application"},
    {"id":"word(tokyo|is|a|city,is)","label":"word(tokyo|is|a|city,is)","role":"application"},
    {"id":"word(tokyo|is|a|city,tokyo)","label":"word(tokyo|is|a|city,tokyo)","role":"application"}
  ],
  "edges": [
    {"from":"a","to":"word(a|city|is|a|place,a)"},
    {"from":"a","to":"word(paris|is|a|city,a)"},
    {"from":"a","to":"word(tokyo|is|a|city,a)"},
    {"from":"a city is a place","to":"cutSentences(a city is a place)"},
    {"from":"a city is a place","to":"cutWords(a city is a place)"},
    {"from":"a city is a place","to":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,a city is a place)"},
    {"from":"a city is a place","to":"sentence(a city is a place,a city is a place)"},
    {"from":"a|city|is|a|place","to":"word(a|city|is|a|place,a)"},
    {"from":"a|city|is|a|place","to":"word(a|city|is|a|place,city)"},
    {"from":"a|city|is|a|place","to":"word(a|city|is|a|place,is)"},
    {"from":"a|city|is|a|place","to":"word(a|city|is|a|place,place)"},
    {"from":"city","to":"word(a|city|is|a|place,city)"},
    {"from":"city","to":"word(paris|is|a|city,city)"},
    {"from":"city","to":"word(the|city|is|new,city)"},
    {"from":"city","to":"word(the|city|is|old,city)"},
    {"from":"city","to":"word(tokyo|is|a|city,city)"},
    {"from":"cutParagraphs()","to":"cutParagraphs(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place)"},
    {"from":"cutParagraphs(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place)","to":"paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place"},
    {"from":"cutSentences()","to":"cutSentences(a city is a place)"},
    {"from":"cutSentences()","to":"cutSentences(paris is a city\nthe city is old)"},
    {"from":"cutSentences()","to":"cutSentences(tokyo is a city\nthe city is new)"},
    {"from":"cutSentences(a city is a place)","to":"a city is a place"},
    {"from":"cutSentences(paris is a city\nthe city is old)","to":"paris is a city|the city is old"},
    {"from":"cutSentences(tokyo is a city\nthe city is new)","to":"tokyo is a city|the city is new"},
    {"from":"cutWords()","to":"cutWords(a city is a place)"},
    {"from":"cutWords()","to":"cutWords(paris is a city)"},
    {"from":"cutWords()","to":"cutWords(the city is new)"},
    {"from":"cutWords()","to":"cutWords(the city is old)"},
    {"from":"cutWords()","to":"cutWords(tokyo is a city)"},
    {"from":"cutWords(a city is a place)","to":"a|city|is|a|place"},
    {"from":"cutWords(paris is a city)","to":"paris|is|a|city"},
    {"from":"cutWords(the city is new)","to":"the|city|is|new"},
    {"from":"cutWords(the city is old)","to":"the|city|is|old"},
    {"from":"cutWords(tokyo is a city)","to":"tokyo|is|a|city"},
    {"from":"is","to":"word(a|city|is|a|place,is)"},
    {"from":"is","to":"word(paris|is|a|city,is)"},
    {"from":"is","to":"word(the|city|is|new,is)"},
    {"from":"is","to":"word(the|city|is|old,is)"},
    {"from":"is","to":"word(tokyo|is|a|city,is)"},
    {"from":"new","to":"word(the|city|is|new,new)"},
    {"from":"old","to":"word(the|city|is|old,old)"},
    {"from":"paragraph()","to":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,a city is a place)"},
    {"from":"paragraph()","to":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,paris is a city\nthe city is old)"},
    {"from":"paragraph()","to":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,tokyo is a city\nthe city is new)"},
    {"from":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,a city is a place)","to":"a city is a place"},
    {"from":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,paris is a city\nthe city is old)","to":"paris is a city\nthe city is old"},
    {"from":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,tokyo is a city\nthe city is new)","to":"tokyo is a city\nthe city is new"},
    {"from":"paris","to":"word(paris|is|a|city,paris)"},
    {"from":"paris is a city","to":"cutWords(paris is a city)"},
    {"from":"paris is a city","to":"sentence(paris is a city|the city is old,paris is a city)"},
    {"from":"paris is a city\nthe city is old","to":"cutSentences(paris is a city\nthe city is old)"},
    {"from":"paris is a city\nthe city is old","to":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,paris is a city\nthe city is old)"},
    {"from":"paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place","to":"cutParagraphs(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place)"},
    {"from":"paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place","to":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,a city is a place)"},
    {"from":"paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place","to":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,paris is a city\nthe city is old)"},
    {"from":"paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place","to":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,tokyo is a city\nthe city is new)"},
    {"from":"paris is a city|the city is old","to":"sentence(paris is a city|the city is old,paris is a city)"},
    {"from":"paris is a city|the city is old","to":"sentence(paris is a city|the city is old,the city is old)"},
    {"from":"paris|is|a|city","to":"word(paris|is|a|city,a)"},
    {"from":"paris|is|a|city","to":"word(paris|is|a|city,city)"},
    {"from":"paris|is|a|city","to":"word(paris|is|a|city,is)"},
    {"from":"paris|is|a|city","to":"word(paris|is|a|city,paris)"},
    {"from":"place","to":"word(a|city|is|a|place,place)"},
    {"from":"sentence()","to":"sentence(a city is a place,a city is a place)"},
    {"from":"sentence()","to":"sentence(paris is a city|the city is old,paris is a city)"},
    {"from":"sentence()","to":"sentence(paris is a city|the city is old,the city is old)"},
    {"from":"sentence()","to":"sentence(tokyo is a city|the city is new,the city is new)"},
    {"from":"sentence()","to":"sentence(tokyo is a city|the city is new,tokyo is a city)"},
    {"from":"sentence(a city is a place,a city is a place)","to":"a city is a place"},
    {"from":"sentence(paris is a city|the city is old,paris is a city)","to":"paris is a city"},
    {"from":"sentence(paris is a city|the city is old,the city is old)","to":"the city is old"},
    {"from":"sentence(tokyo is a city|the city is new,the city is new)","to":"the city is new"},
    {"from":"sentence(tokyo is a city|the city is new,tokyo is a city)","to":"tokyo is a city"},
    {"from":"the","to":"word(the|city|is|new,the)"},
    {"from":"the","to":"word(the|city|is|old,the)"},
    {"from":"the city is new","to":"cutWords(the city is new)"},
    {"from":"the city is new","to":"sentence(tokyo is a city|the city is new,the city is new)"},
    {"from":"the city is old","to":"cutWords(the city is old)"},
    {"from":"the city is old","to":"sentence(paris is a city|the city is old,the city is old)"},
    {"from":"the|city|is|new","to":"word(the|city|is|new,city)"},
    {"from":"the|city|is|new","to":"word(the|city|is|new,is)"},
    {"from":"the|city|is|new","to":"word(the|city|is|new,new)"},
    {"from":"the|city|is|new","to":"word(the|city|is|new,the)"},
    {"from":"the|city|is|old","to":"word(the|city|is|old,city)"},
    {"from":"the|city|is|old","to":"word(the|city|is|old,is)"},
    {"from":"the|city|is|old","to":"word(the|city|is|old,old)"},
    {"from":"the|city|is|old","to":"word(the|city|is|old,the)"},
    {"from":"tokyo","to":"word(tokyo|is|a|city,tokyo)"},
    {"from":"tokyo is a city","to":"cutWords(tokyo is a city)"},
    {"from":"tokyo is a city","to":"sentence(tokyo is a city|the city is new,tokyo is a city)"},
    {"from":"tokyo is a city\nthe city is new","to":"cutSentences(tokyo is a city\nthe city is new)"},
    {"from":"tokyo is a city\nthe city is new","to":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,tokyo is a city\nthe city is new)"},
    {"from":"tokyo is a city|the city is new","to":"sentence(tokyo is a city|the city is new,the city is new)"},
    {"from":"tokyo is a city|the city is new","to":"sentence(tokyo is a city|the city is new,tokyo is a city)"},
    {"from":"tokyo|is|a|city","to":"word(tokyo|is|a|city,a)"},
    {"from":"tokyo|is|a|city","to":"word(tokyo|is|a|city,city)"},
    {"from":"tokyo|is|a|city","to":"word(tokyo|is|a|city,is)"},
    {"from":"tokyo|is|a|city","to":"word(tokyo|is|a|city,tokyo)"},
    {"from":"word()","to":"word(a|city|is|a|place,a)"},
    {"from":"word()","to":"word(a|city|is|a|place,city)"},
    {"from":"word()","to":"word(a|city|is|a|place,is)"},
    {"from":"word()","to":"word(a|city|is|a|place,place)"},
    {"from":"word()","to":"word(paris|is|a|city,a)"},
    {"from":"word()","to":"word(paris|is|a|city,city)"},
    {"from":"word()","to":"word(paris|is|a|city,is)"},
    {"from":"word()","to":"word(paris|is|a|city,paris)"},
    {"from":"word()","to":"word(the|city|is|new,city)"},
    {"from":"word()","to":"word(the|city|is|new,is)"},
    {"from":"word()","to":"word(the|city|is|new,new)"},
    {"from":"word()","to":"word(the|city|is|new,the)"},
    {"from":"word()","to":"word(the|city|is|old,city)"},
    {"from":"word()","to":"word(the|city|is|old,is)"},
    {"from":"word()","to":"word(the|city|is|old,old)"},
    {"from":"word()","to":"word(the|city|is|old,the)"},
    {"from":"word()","to":"word(tokyo|is|a|city,a)"},
    {"from":"word()","to":"word(tokyo|is|a|city,city)"},
    {"from":"word()","to":"word(tokyo|is|a|city,is)"},
    {"from":"word()","to":"word(tokyo|is|a|city,tokyo)"},
    {"from":"word(a|city|is|a|place,a)","to":"a"},
    {"from":"word(a|city|is|a|place,city)","to":"city"},
    {"from":"word(a|city|is|a|place,is)","to":"is"},
    {"from":"word(a|city|is|a|place,place)","to":"place"},
    {"from":"word(paris|is|a|city,a)","to":"a"},
    {"from":"word(paris|is|a|city,city)","to":"city"},
    {"from":"word(paris|is|a|city,is)","to":"is"},
    {"from":"word(paris|is|a|city,paris)","to":"paris"},
    {"from":"word(the|city|is|new,city)","to":"city"},
    {"from":"word(the|city|is|new,is)","to":"is"},
    {"from":"word(the|city|is|new,new)","to":"new"},
    {"from":"word(the|city|is|new,the)","to":"the"},
    {"from":"word(the|city|is|old,city)","to":"city"},
    {"from":"word(the|city|is|old,is)","to":"is"},
    {"from":"word(the|city|is|old,old)","to":"old"},
    {"from":"word(the|city|is|old,the)","to":"the"},
    {"from":"word(tokyo|is|a|city,a)","to":"a"},
    {"from":"word(tokyo|is|a|city,city)","to":"city"},
    {"from":"word(tokyo|is|a|city,is)","to":"is"},
    {"from":"word(tokyo|is|a|city,tokyo)","to":"tokyo"}
  ],
  "pivot": {
    "subjects": [
      "a city is a place",
      "a|city|is|a|place",
      "paris is a city",
      "paris is a city\nthe city is old",
      "paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place",
      "paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place",
      "paris is a city|the city is old",
      "paris|is|a|city",
      "the city is new",
      "the city is old",
      "the|city|is|new",
      "the|city|is|old",
      "tokyo is a city",
      "tokyo is a city\nthe city is new",
      "tokyo is a city|the city is new",
      "tokyo|is|a|city"
    ],
    "columns": [
      "cutParagraphs",
      "cutSentences",
      "cutWords",
      "paragraph(·,a city is a place)",
      "paragraph(·,paris is a city\nthe city is old)",
      "paragraph(·,tokyo is a city\nthe city is new)",
      "sentence",
      "sentence(·,paris is a city)",
      "sentence(·,the city is new)",
      "sentence(·,the city is old)",
      "sentence(·,tokyo is a city)",
      "word(·,a)",
      "word(·,city)",
      "word(·,is)",
      "word(·,new)",
      "word(·,old)",
      "word(·,paris)",
      "word(·,place)",
      "word(·,the)",
      "word(·,tokyo)"
    ],
    "cells": [
      {"s":"a city is a place","c":"cutSentences","res":"a city is a place","app":"cutSentences(a city is a place)"},
      {"s":"a city is a place","c":"cutWords","res":"a|city|is|a|place","app":"cutWords(a city is a place)"},
      {"s":"a city is a place","c":"sentence","res":"a city is a place","app":"sentence(a city is a place,a city is a place)"},
      {"s":"a|city|is|a|place","c":"word(·,a)","res":"a","app":"word(a|city|is|a|place,a)"},
      {"s":"a|city|is|a|place","c":"word(·,city)","res":"city","app":"word(a|city|is|a|place,city)"},
      {"s":"a|city|is|a|place","c":"word(·,is)","res":"is","app":"word(a|city|is|a|place,is)"},
      {"s":"a|city|is|a|place","c":"word(·,place)","res":"place","app":"word(a|city|is|a|place,place)"},
      {"s":"paris is a city","c":"cutWords","res":"paris|is|a|city","app":"cutWords(paris is a city)"},
      {"s":"paris is a city\nthe city is old","c":"cutSentences","res":"paris is a city|the city is old","app":"cutSentences(paris is a city\nthe city is old)"},
      {"s":"paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place","c":"cutParagraphs","res":"paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place","app":"cutParagraphs(paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place)"},
      {"s":"paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place","c":"paragraph(·,a city is a place)","res":"a city is a place","app":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,a city is a place)"},
      {"s":"paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place","c":"paragraph(·,paris is a city\nthe city is old)","res":"paris is a city\nthe city is old","app":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,paris is a city\nthe city is old)"},
      {"s":"paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place","c":"paragraph(·,tokyo is a city\nthe city is new)","res":"tokyo is a city\nthe city is new","app":"paragraph(paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place,tokyo is a city\nthe city is new)"},
      {"s":"paris is a city|the city is old","c":"sentence(·,paris is a city)","res":"paris is a city","app":"sentence(paris is a city|the city is old,paris is a city)"},
      {"s":"paris is a city|the city is old","c":"sentence(·,the city is old)","res":"the city is old","app":"sentence(paris is a city|the city is old,the city is old)"},
      {"s":"paris|is|a|city","c":"word(·,a)","res":"a","app":"word(paris|is|a|city,a)"},
      {"s":"paris|is|a|city","c":"word(·,city)","res":"city","app":"word(paris|is|a|city,city)"},
      {"s":"paris|is|a|city","c":"word(·,is)","res":"is","app":"word(paris|is|a|city,is)"},
      {"s":"paris|is|a|city","c":"word(·,paris)","res":"paris","app":"word(paris|is|a|city,paris)"},
      {"s":"the city is new","c":"cutWords","res":"the|city|is|new","app":"cutWords(the city is new)"},
      {"s":"the city is old","c":"cutWords","res":"the|city|is|old","app":"cutWords(the city is old)"},
      {"s":"the|city|is|new","c":"word(·,city)","res":"city","app":"word(the|city|is|new,city)"},
      {"s":"the|city|is|new","c":"word(·,is)","res":"is","app":"word(the|city|is|new,is)"},
      {"s":"the|city|is|new","c":"word(·,new)","res":"new","app":"word(the|city|is|new,new)"},
      {"s":"the|city|is|new","c":"word(·,the)","res":"the","app":"word(the|city|is|new,the)"},
      {"s":"the|city|is|old","c":"word(·,city)","res":"city","app":"word(the|city|is|old,city)"},
      {"s":"the|city|is|old","c":"word(·,is)","res":"is","app":"word(the|city|is|old,is)"},
      {"s":"the|city|is|old","c":"word(·,old)","res":"old","app":"word(the|city|is|old,old)"},
      {"s":"the|city|is|old","c":"word(·,the)","res":"the","app":"word(the|city|is|old,the)"},
      {"s":"tokyo is a city","c":"cutWords","res":"tokyo|is|a|city","app":"cutWords(tokyo is a city)"},
      {"s":"tokyo is a city\nthe city is new","c":"cutSentences","res":"tokyo is a city|the city is new","app":"cutSentences(tokyo is a city\nthe city is new)"},
      {"s":"tokyo is a city|the city is new","c":"sentence(·,the city is new)","res":"the city is new","app":"sentence(tokyo is a city|the city is new,the city is new)"},
      {"s":"tokyo is a city|the city is new","c":"sentence(·,tokyo is a city)","res":"tokyo is a city","app":"sentence(tokyo is a city|the city is new,tokyo is a city)"},
      {"s":"tokyo|is|a|city","c":"word(·,a)","res":"a","app":"word(tokyo|is|a|city,a)"},
      {"s":"tokyo|is|a|city","c":"word(·,city)","res":"city","app":"word(tokyo|is|a|city,city)"},
      {"s":"tokyo|is|a|city","c":"word(·,is)","res":"is","app":"word(tokyo|is|a|city,is)"},
      {"s":"tokyo|is|a|city","c":"word(·,tokyo)","res":"tokyo","app":"word(tokyo|is|a|city,tokyo)"}
    ]
  },
  "tables": [
    {"cols":["cutWords"],"rows":["paris is a city","the city is new","the city is old","tokyo is a city"]},
    {"cols":["cutSentences"],"rows":["paris is a city\nthe city is old","tokyo is a city\nthe city is new"]},
    {"cols":["word(·,a)","word(·,city)","word(·,is)","word(·,place)"],"rows":["a|city|is|a|place"]},
    {"cols":["word(·,a)","word(·,city)","word(·,is)","word(·,paris)"],"rows":["paris|is|a|city"]},
    {"cols":["word(·,city)","word(·,is)","word(·,new)","word(·,the)"],"rows":["the|city|is|new"]},
    {"cols":["word(·,city)","word(·,is)","word(·,old)","word(·,the)"],"rows":["the|city|is|old"]},
    {"cols":["word(·,a)","word(·,city)","word(·,is)","word(·,tokyo)"],"rows":["tokyo|is|a|city"]},
    {"cols":["cutSentences","cutWords","sentence"],"rows":["a city is a place"]},
    {"cols":["paragraph(·,a city is a place)","paragraph(·,paris is a city\nthe city is old)","paragraph(·,tokyo is a city\nthe city is new)"],"rows":["paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place"]},
    {"cols":["sentence(·,paris is a city)","sentence(·,the city is old)"],"rows":["paris is a city|the city is old"]},
    {"cols":["sentence(·,the city is new)","sentence(·,tokyo is a city)"],"rows":["tokyo is a city|the city is new"]},
    {"cols":["cutParagraphs"],"rows":["paris is a city\nthe city is old\n\ntokyo is a city\nthe city is new\n\na city is a place"]}
  ],
  "chains": [],
  "listings": [
    {"fn":"paragraph","from":"paris is a city\nthe city is old|tokyo is a city\nthe city is new|a city is a place","items":["a city is a place","paris is a city\nthe city is old","tokyo is a city\nthe city is new"]},
    {"fn":"sentence","from":"paris is a city|the city is old","items":["paris is a city","the city is old"]},
    {"fn":"sentence","from":"tokyo is a city|the city is new","items":["the city is new","tokyo is a city"]},
    {"fn":"word","from":"a|city|is|a|place","items":["a","city","is","place"]},
    {"fn":"word","from":"paris|is|a|city","items":["a","city","is","paris"]},
    {"fn":"word","from":"the|city|is|new","items":["city","is","new","the"]},
    {"fn":"word","from":"the|city|is|old","items":["city","is","old","the"]},
    {"fn":"word","from":"tokyo|is|a|city","items":["a","city","is","tokyo"]}
  ]
};
