window.GRAPH = {
  "nodes": [
    {"id":"192.168.1.2","label":"192.168.1.2","role":"value"},
    {"id":"8.8.8.8","label":"8.8.8.8","role":"value"},
    {"id":"8080","label":"8080","role":"value"},
    {"id":"db01.internal","label":"db01.internal","role":"value"},
    {"id":"hello world","label":"hello world","role":"value"},
    {"id":"isEmail()","label":"isEmail()","role":"function"},
    {"id":"isEmail(user@db.local)","label":"isEmail(user@db.local)","role":"application"},
    {"id":"isHost()","label":"isHost()","role":"function"},
    {"id":"isHost(192.168.1.2)","label":"isHost(192.168.1.2)","role":"application"},
    {"id":"isHost(8.8.8.8)","label":"isHost(8.8.8.8)","role":"application"},
    {"id":"isHost(db01.internal)","label":"isHost(db01.internal)","role":"application"},
    {"id":"isIP()","label":"isIP()","role":"function"},
    {"id":"isIP(192.168.1.2)","label":"isIP(192.168.1.2)","role":"application"},
    {"id":"isIP(8.8.8.8)","label":"isIP(8.8.8.8)","role":"application"},
    {"id":"isInternalIP()","label":"isInternalIP()","role":"function"},
    {"id":"isInternalIP(192.168.1.2)","label":"isInternalIP(192.168.1.2)","role":"application"},
    {"id":"isNumber()","label":"isNumber()","role":"function"},
    {"id":"isNumber(8080)","label":"isNumber(8080)","role":"application"},
    {"id":"isPort()","label":"isPort()","role":"function"},
    {"id":"isPort(8080)","label":"isPort(8080)","role":"application"},
    {"id":"isString()","label":"isString()","role":"function"},
    {"id":"isString(192.168.1.2)","label":"isString(192.168.1.2)","role":"application"},
    {"id":"isString(8.8.8.8)","label":"isString(8.8.8.8)","role":"application"},
    {"id":"isString(8080)","label":"isString(8080)","role":"application"},
    {"id":"isString(db01.internal)","label":"isString(db01.internal)","role":"application"},
    {"id":"isString(hello world)","label":"isString(hello world)","role":"application"},
    {"id":"isString(mystery-blob)","label":"isString(mystery-blob)","role":"application"},
    {"id":"isString(user@db.local)","label":"isString(user@db.local)","role":"application"},
    {"id":"mystery-blob","label":"mystery-blob","role":"value"},
    {"id":"user@db.local","label":"user@db.local","role":"value"},
    {"id":"∅","label":"∅","role":"value"}
  ],
  "edges": [
    {"from":"192.168.1.2","to":"isHost(192.168.1.2)"},
    {"from":"192.168.1.2","to":"isIP(192.168.1.2)"},
    {"from":"192.168.1.2","to":"isInternalIP(192.168.1.2)"},
    {"from":"192.168.1.2","to":"isString(192.168.1.2)"},
    {"from":"8.8.8.8","to":"isHost(8.8.8.8)"},
    {"from":"8.8.8.8","to":"isIP(8.8.8.8)"},
    {"from":"8.8.8.8","to":"isString(8.8.8.8)"},
    {"from":"8080","to":"isNumber(8080)"},
    {"from":"8080","to":"isPort(8080)"},
    {"from":"8080","to":"isString(8080)"},
    {"from":"db01.internal","to":"isHost(db01.internal)"},
    {"from":"db01.internal","to":"isString(db01.internal)"},
    {"from":"hello world","to":"isString(hello world)"},
    {"from":"isEmail()","to":"isEmail(user@db.local)"},
    {"from":"isEmail(user@db.local)","to":"user@db.local"},
    {"from":"isHost()","to":"isHost(192.168.1.2)"},
    {"from":"isHost()","to":"isHost(8.8.8.8)"},
    {"from":"isHost()","to":"isHost(db01.internal)"},
    {"from":"isHost(192.168.1.2)","to":"192.168.1.2"},
    {"from":"isHost(8.8.8.8)","to":"8.8.8.8"},
    {"from":"isHost(db01.internal)","to":"db01.internal"},
    {"from":"isIP()","to":"isIP(192.168.1.2)"},
    {"from":"isIP()","to":"isIP(8.8.8.8)"},
    {"from":"isIP(192.168.1.2)","to":"192.168.1.2"},
    {"from":"isIP(8.8.8.8)","to":"8.8.8.8"},
    {"from":"isInternalIP()","to":"isInternalIP(192.168.1.2)"},
    {"from":"isInternalIP(192.168.1.2)","to":"192.168.1.2"},
    {"from":"isNumber()","to":"isNumber(8080)"},
    {"from":"isNumber(8080)","to":"8080"},
    {"from":"isPort()","to":"isPort(8080)"},
    {"from":"isPort(8080)","to":"8080"},
    {"from":"isString()","to":"isString(192.168.1.2)"},
    {"from":"isString()","to":"isString(8.8.8.8)"},
    {"from":"isString()","to":"isString(8080)"},
    {"from":"isString()","to":"isString(db01.internal)"},
    {"from":"isString()","to":"isString(hello world)"},
    {"from":"isString()","to":"isString(mystery-blob)"},
    {"from":"isString()","to":"isString(user@db.local)"},
    {"from":"isString(192.168.1.2)","to":"192.168.1.2"},
    {"from":"isString(8.8.8.8)","to":"8.8.8.8"},
    {"from":"isString(8080)","to":"8080"},
    {"from":"isString(db01.internal)","to":"db01.internal"},
    {"from":"isString(hello world)","to":"hello world"},
    {"from":"isString(mystery-blob)","to":"mystery-blob"},
    {"from":"isString(user@db.local)","to":"user@db.local"},
    {"from":"mystery-blob","to":"isString(mystery-blob)"},
    {"from":"user@db.local","to":"isEmail(user@db.local)"},
    {"from":"user@db.local","to":"isString(user@db.local)"}
  ],
  "pivot": {
    "subjects": [
      "192.168.1.2",
      "8.8.8.8",
      "8080",
      "db01.internal",
      "hello world",
      "mystery-blob",
      "user@db.local"
    ],
    "columns": [
      "isEmail",
      "isHost",
      "isIP",
      "isInternalIP",
      "isNumber",
      "isPort",
      "isString"
    ],
    "cells": [
      {"s":"192.168.1.2","c":"isHost","res":"192.168.1.2","app":"isHost(192.168.1.2)"},
      {"s":"192.168.1.2","c":"isInternalIP","res":"192.168.1.2","app":"isInternalIP(192.168.1.2)"},
      {"s":"192.168.1.2","c":"isIP","res":"192.168.1.2","app":"isIP(192.168.1.2)"},
      {"s":"192.168.1.2","c":"isString","res":"192.168.1.2","app":"isString(192.168.1.2)"},
      {"s":"8.8.8.8","c":"isHost","res":"8.8.8.8","app":"isHost(8.8.8.8)"},
      {"s":"8.8.8.8","c":"isIP","res":"8.8.8.8","app":"isIP(8.8.8.8)"},
      {"s":"8.8.8.8","c":"isString","res":"8.8.8.8","app":"isString(8.8.8.8)"},
      {"s":"8080","c":"isNumber","res":"8080","app":"isNumber(8080)"},
      {"s":"8080","c":"isPort","res":"8080","app":"isPort(8080)"},
      {"s":"8080","c":"isString","res":"8080","app":"isString(8080)"},
      {"s":"db01.internal","c":"isHost","res":"db01.internal","app":"isHost(db01.internal)"},
      {"s":"db01.internal","c":"isString","res":"db01.internal","app":"isString(db01.internal)"},
      {"s":"hello world","c":"isString","res":"hello world","app":"isString(hello world)"},
      {"s":"mystery-blob","c":"isString","res":"mystery-blob","app":"isString(mystery-blob)"},
      {"s":"user@db.local","c":"isEmail","res":"user@db.local","app":"isEmail(user@db.local)"},
      {"s":"user@db.local","c":"isString","res":"user@db.local","app":"isString(user@db.local)"}
    ]
  },
  "tables": [
    {"cols":["isString"],"rows":["hello world","mystery-blob"]},
    {"cols":["isHost","isIP","isInternalIP","isString"],"rows":["192.168.1.2"]},
    {"cols":["isHost","isIP","isString"],"rows":["8.8.8.8"]},
    {"cols":["isNumber","isPort","isString"],"rows":["8080"]},
    {"cols":["isHost","isString"],"rows":["db01.internal"]},
    {"cols":["isEmail","isString"],"rows":["user@db.local"]}
  ],
  "chains": [],
  "listings": []
};
